/****************************************************************************
**
** Metadata for EARTHLib generated by dumpcpp v5.14.1 using
** D:\Qt\Qt5.14.1\5.14.1\msvc2017_64\bin\dumpcpp.exe googleearth.exe
** from the type library googleearth.exe
**
****************************************************************************/

#define QAX_DUMPCPP_EARTHLIB_NOINLINES
#include "earthlib.h"
#include <OAIdl.h>

using namespace EARTHLib;

struct qt_meta_stringdata_all_t {
    QByteArrayData data[238];
    char stringdata0[3354];
};
#define QT_MOC_LITERAL(idx, ofs, len, table) \
    Q_STATIC_BYTE_ARRAY_DATA_HEADER_INITIALIZER_WITH_OFFSET(len, \
    offsetof(qt_meta_stringdata_all_t, stringdata##table) + ofs \
        - idx * sizeof(QByteArrayData) \
    )
static const qt_meta_stringdata_all_t qt_meta_stringdata_all = {
    {
QT_MOC_LITERAL(0, 0, 23, 0),
QT_MOC_LITERAL(1, 24, 11, 0),
QT_MOC_LITERAL(2, 36, 14, 0),
QT_MOC_LITERAL(3, 51, 9, 0),
QT_MOC_LITERAL(4, 61, 0, 0),
QT_MOC_LITERAL(5, 62, 4, 0),
QT_MOC_LITERAL(6, 67, 6, 0),
QT_MOC_LITERAL(7, 74, 4, 0),
QT_MOC_LITERAL(8, 79, 4, 0),
QT_MOC_LITERAL(9, 84, 15, 0),
QT_MOC_LITERAL(10, 100, 4, 0),
QT_MOC_LITERAL(11, 105, 6, 0),
QT_MOC_LITERAL(12, 112, 4, 0),
QT_MOC_LITERAL(13, 117, 4, 0),
QT_MOC_LITERAL(14, 122, 9, 0),
QT_MOC_LITERAL(15, 132, 14, 0),
QT_MOC_LITERAL(16, 147, 15, 0),
QT_MOC_LITERAL(17, 163, 16, 0),
QT_MOC_LITERAL(18, 180, 11, 0),
QT_MOC_LITERAL(19, 192, 4, 0),
QT_MOC_LITERAL(20, 197, 16, 0),
QT_MOC_LITERAL(21, 214, 4, 0),
QT_MOC_LITERAL(22, 219, 21, 0),
QT_MOC_LITERAL(23, 241, 18, 0),
QT_MOC_LITERAL(24, 260, 21, 0),
QT_MOC_LITERAL(25, 282, 11, 0),
QT_MOC_LITERAL(26, 294, 11, 0),
QT_MOC_LITERAL(27, 306, 33, 0),
QT_MOC_LITERAL(28, 340, 18, 0),
QT_MOC_LITERAL(29, 359, 8, 0),
QT_MOC_LITERAL(30, 368, 8, 0),
QT_MOC_LITERAL(31, 377, 13, 0),
QT_MOC_LITERAL(32, 391, 18, 0),
QT_MOC_LITERAL(33, 410, 23, 0),
QT_MOC_LITERAL(34, 434, 13, 0),
QT_MOC_LITERAL(35, 448, 8, 0),
QT_MOC_LITERAL(36, 457, 11, 0),
QT_MOC_LITERAL(37, 469, 8, 0),
QT_MOC_LITERAL(38, 478, 7, 0),
QT_MOC_LITERAL(39, 486, 5, 0),
QT_MOC_LITERAL(40, 492, 6, 0),
QT_MOC_LITERAL(41, 499, 11, 0),
QT_MOC_LITERAL(42, 511, 8, 0),
QT_MOC_LITERAL(43, 520, 16, 0),
QT_MOC_LITERAL(44, 537, 14, 0),
QT_MOC_LITERAL(45, 552, 7, 0),
QT_MOC_LITERAL(46, 560, 17, 0),
QT_MOC_LITERAL(47, 578, 14, 0),
QT_MOC_LITERAL(48, 593, 9, 0),
QT_MOC_LITERAL(49, 603, 6, 0),
QT_MOC_LITERAL(50, 610, 5, 0),
QT_MOC_LITERAL(51, 616, 15, 0),
QT_MOC_LITERAL(52, 632, 3, 0),
QT_MOC_LITERAL(53, 636, 3, 0),
QT_MOC_LITERAL(54, 640, 3, 0),
QT_MOC_LITERAL(55, 644, 41, 0),
QT_MOC_LITERAL(56, 686, 7, 0),
QT_MOC_LITERAL(57, 694, 5, 0),
QT_MOC_LITERAL(58, 700, 4, 0),
QT_MOC_LITERAL(59, 705, 7, 0),
QT_MOC_LITERAL(60, 713, 24, 0),
QT_MOC_LITERAL(61, 738, 21, 0),
QT_MOC_LITERAL(62, 760, 14, 0),
QT_MOC_LITERAL(63, 775, 7, 0),
QT_MOC_LITERAL(64, 783, 22, 0),
QT_MOC_LITERAL(65, 806, 19, 0),
QT_MOC_LITERAL(66, 826, 23, 0),
QT_MOC_LITERAL(67, 850, 16, 0),
QT_MOC_LITERAL(68, 867, 20, 0),
QT_MOC_LITERAL(69, 888, 27, 0),
QT_MOC_LITERAL(70, 916, 14, 0),
QT_MOC_LITERAL(71, 931, 18, 0),
QT_MOC_LITERAL(72, 950, 14, 0),
QT_MOC_LITERAL(73, 965, 26, 0),
QT_MOC_LITERAL(74, 992, 12, 0),
QT_MOC_LITERAL(75, 1005, 12, 0),
QT_MOC_LITERAL(76, 1018, 12, 0),
QT_MOC_LITERAL(77, 1031, 11, 0),
QT_MOC_LITERAL(78, 1043, 15, 0),
QT_MOC_LITERAL(79, 1059, 18, 0),
QT_MOC_LITERAL(80, 1078, 5, 0),
QT_MOC_LITERAL(81, 1084, 6, 0),
QT_MOC_LITERAL(82, 1091, 6, 0),
QT_MOC_LITERAL(83, 1098, 9, 0),
QT_MOC_LITERAL(84, 1108, 24, 0),
QT_MOC_LITERAL(85, 1133, 5, 0),
QT_MOC_LITERAL(86, 1139, 6, 0),
QT_MOC_LITERAL(87, 1146, 7, 0),
QT_MOC_LITERAL(88, 1154, 7, 0),
QT_MOC_LITERAL(89, 1162, 9, 0),
QT_MOC_LITERAL(90, 1172, 7, 0),
QT_MOC_LITERAL(91, 1180, 19, 0),
QT_MOC_LITERAL(92, 1200, 22, 0),
QT_MOC_LITERAL(93, 1223, 12, 0),
QT_MOC_LITERAL(94, 1236, 22, 0),
QT_MOC_LITERAL(95, 1259, 26, 0),
QT_MOC_LITERAL(96, 1286, 18, 0),
QT_MOC_LITERAL(97, 1305, 24, 0),
QT_MOC_LITERAL(98, 1330, 7, 0),
QT_MOC_LITERAL(99, 1338, 23, 0),
QT_MOC_LITERAL(100, 1362, 10, 0),
QT_MOC_LITERAL(101, 1373, 21, 0),
QT_MOC_LITERAL(102, 1395, 18, 0),
QT_MOC_LITERAL(103, 1414, 25, 0),
QT_MOC_LITERAL(104, 1440, 22, 0),
QT_MOC_LITERAL(105, 1463, 21, 0),
QT_MOC_LITERAL(106, 1485, 18, 0),
QT_MOC_LITERAL(107, 1504, 22, 0),
QT_MOC_LITERAL(108, 1527, 19, 0),
QT_MOC_LITERAL(109, 1547, 8, 0),
QT_MOC_LITERAL(110, 1556, 7, 0),
QT_MOC_LITERAL(111, 1564, 24, 0),
QT_MOC_LITERAL(112, 1589, 4, 0),
QT_MOC_LITERAL(113, 1594, 5, 0),
QT_MOC_LITERAL(114, 1600, 5, 0),
QT_MOC_LITERAL(115, 1606, 4, 0),
QT_MOC_LITERAL(116, 1611, 20, 0),
QT_MOC_LITERAL(117, 1632, 11, 0),
QT_MOC_LITERAL(118, 1644, 9, 0),
QT_MOC_LITERAL(119, 1654, 9, 0),
QT_MOC_LITERAL(120, 1664, 13, 0),
QT_MOC_LITERAL(121, 1678, 10, 0),
QT_MOC_LITERAL(122, 1689, 7, 0),
QT_MOC_LITERAL(123, 1697, 11, 0),
QT_MOC_LITERAL(124, 1709, 12, 0),
QT_MOC_LITERAL(125, 1722, 16, 0),
QT_MOC_LITERAL(126, 1739, 30, 0),
QT_MOC_LITERAL(127, 1770, 4, 0),
QT_MOC_LITERAL(128, 1775, 5, 0),
QT_MOC_LITERAL(129, 1781, 5, 0),
QT_MOC_LITERAL(130, 1787, 8, 0),
QT_MOC_LITERAL(131, 1796, 9, 0),
QT_MOC_LITERAL(132, 1806, 25, 0),
QT_MOC_LITERAL(133, 1832, 9, 0),
QT_MOC_LITERAL(134, 1842, 8, 0),
QT_MOC_LITERAL(135, 1851, 7, 0),
QT_MOC_LITERAL(136, 1859, 17, 0),
QT_MOC_LITERAL(137, 1877, 5, 0),
QT_MOC_LITERAL(138, 1883, 13, 0),
QT_MOC_LITERAL(139, 1897, 8, 0),
QT_MOC_LITERAL(140, 1906, 6, 0),
QT_MOC_LITERAL(141, 1913, 3, 0),
QT_MOC_LITERAL(142, 1917, 7, 0),
QT_MOC_LITERAL(143, 1925, 4, 0),
QT_MOC_LITERAL(144, 1930, 9, 0),
QT_MOC_LITERAL(145, 1940, 6, 0),
QT_MOC_LITERAL(146, 1947, 8, 0),
QT_MOC_LITERAL(147, 1956, 5, 0),
QT_MOC_LITERAL(148, 1962, 9, 0),
QT_MOC_LITERAL(149, 1972, 6, 0),
QT_MOC_LITERAL(150, 1979, 11, 0),
QT_MOC_LITERAL(151, 1991, 7, 0),
QT_MOC_LITERAL(152, 1999, 4, 0),
QT_MOC_LITERAL(153, 2004, 7, 0),
QT_MOC_LITERAL(154, 2012, 4, 0),
QT_MOC_LITERAL(155, 2017, 27, 0),
QT_MOC_LITERAL(156, 2045, 8, 0),
QT_MOC_LITERAL(157, 2054, 8, 0),
QT_MOC_LITERAL(158, 2063, 9, 0),
QT_MOC_LITERAL(159, 2073, 18, 0),
QT_MOC_LITERAL(160, 2092, 25, 0),
QT_MOC_LITERAL(161, 2118, 27, 0),
QT_MOC_LITERAL(162, 2146, 11, 0),
QT_MOC_LITERAL(163, 2158, 9, 0),
QT_MOC_LITERAL(164, 2168, 6, 0),
QT_MOC_LITERAL(165, 2175, 13, 0),
QT_MOC_LITERAL(166, 2189, 10, 0),
QT_MOC_LITERAL(167, 2200, 4, 0),
QT_MOC_LITERAL(168, 2205, 8, 0),
QT_MOC_LITERAL(169, 2214, 29, 0),
QT_MOC_LITERAL(170, 2244, 12, 0),
QT_MOC_LITERAL(171, 2257, 10, 0),
QT_MOC_LITERAL(172, 2268, 18, 0),
QT_MOC_LITERAL(173, 2287, 6, 0),
QT_MOC_LITERAL(174, 2294, 12, 0),
QT_MOC_LITERAL(175, 2307, 32, 0),
QT_MOC_LITERAL(176, 2340, 5, 0),
QT_MOC_LITERAL(177, 2346, 4, 0),
QT_MOC_LITERAL(178, 2351, 22, 0),
QT_MOC_LITERAL(179, 2374, 19, 0),
QT_MOC_LITERAL(180, 2394, 18, 0),
QT_MOC_LITERAL(181, 2413, 16, 0),
QT_MOC_LITERAL(182, 2430, 7, 0),
QT_MOC_LITERAL(183, 2438, 24, 0),
QT_MOC_LITERAL(184, 2463, 15, 0),
QT_MOC_LITERAL(185, 2479, 22, 0),
QT_MOC_LITERAL(186, 2502, 13, 0),
QT_MOC_LITERAL(187, 2516, 23, 0),
QT_MOC_LITERAL(188, 2540, 14, 0),
QT_MOC_LITERAL(189, 2555, 26, 0),
QT_MOC_LITERAL(190, 2582, 17, 0),
QT_MOC_LITERAL(191, 2600, 28, 0),
QT_MOC_LITERAL(192, 2629, 19, 0),
QT_MOC_LITERAL(193, 2649, 31, 0),
QT_MOC_LITERAL(194, 2681, 22, 0),
QT_MOC_LITERAL(195, 2704, 19, 0),
QT_MOC_LITERAL(196, 2724, 10, 0),
QT_MOC_LITERAL(197, 2735, 29, 0),
QT_MOC_LITERAL(198, 2765, 20, 0),
QT_MOC_LITERAL(199, 2786, 26, 0),
QT_MOC_LITERAL(200, 2813, 17, 0),
QT_MOC_LITERAL(201, 2831, 21, 0),
QT_MOC_LITERAL(202, 2853, 12, 0),
QT_MOC_LITERAL(203, 2866, 11, 0),
QT_MOC_LITERAL(204, 2878, 7, 0),
QT_MOC_LITERAL(205, 2886, 8, 0),
QT_MOC_LITERAL(206, 2895, 15, 0),
QT_MOC_LITERAL(207, 2911, 19, 0),
QT_MOC_LITERAL(208, 2931, 5, 0),
QT_MOC_LITERAL(209, 2937, 6, 0),
QT_MOC_LITERAL(210, 2944, 11, 0),
QT_MOC_LITERAL(211, 2956, 12, 0),
QT_MOC_LITERAL(212, 2969, 7, 0),
QT_MOC_LITERAL(213, 2977, 17, 0),
QT_MOC_LITERAL(214, 2995, 4, 0),
QT_MOC_LITERAL(215, 3000, 5, 0),
QT_MOC_LITERAL(216, 3006, 5, 0),
QT_MOC_LITERAL(217, 3012, 5, 0),
QT_MOC_LITERAL(218, 3018, 25, 0),
QT_MOC_LITERAL(219, 3044, 7, 0),
QT_MOC_LITERAL(220, 3052, 19, 0),
QT_MOC_LITERAL(221, 3072, 7, 0),
QT_MOC_LITERAL(222, 3080, 4, 0),
QT_MOC_LITERAL(223, 3085, 13, 0),
QT_MOC_LITERAL(224, 3099, 18, 0),
QT_MOC_LITERAL(225, 3118, 15, 0),
QT_MOC_LITERAL(226, 3134, 22, 0),
QT_MOC_LITERAL(227, 3157, 21, 0),
QT_MOC_LITERAL(228, 3179, 11, 0),
QT_MOC_LITERAL(229, 3191, 12, 0),
QT_MOC_LITERAL(230, 3204, 24, 0),
QT_MOC_LITERAL(231, 3229, 20, 0),
QT_MOC_LITERAL(232, 3250, 20, 0),
QT_MOC_LITERAL(233, 3271, 11, 0),
QT_MOC_LITERAL(234, 3283, 23, 0),
QT_MOC_LITERAL(235, 3307, 14, 0),
QT_MOC_LITERAL(236, 3322, 19, 0),
QT_MOC_LITERAL(237, 3342, 10, 0)
    },
    "EARTHLib::ApplicationGE\0Interface 0\0IApplicationGE\0exception\0\0code\0source\0"
    "disc\0help\0propertyChanged\0name\0signal\0argc\0argv\0GetCamera\0ICameraInfoGE*\0"
    "considerTerrain\0GetFeatureByHref\0IFeatureGE*\0href\0GetFeatureByName\0Name\0"
    "GetHighlightedFeature\0GetLayersDatabases\0IFeatureCollectionGE*\0GetMainHwnd\0"
    "GetMyPlaces\0GetPointOnTerrainFromScreenCoords\0IPointOnTerrainGE*\0screen_x\0"
    "screen_y\0GetRenderHwnd\0GetTemporaryPlaces\0HideDescriptionBalloons\0IsInitialized\0"
    "IsOnline\0LoadKmlData\0QString&\0kmlData\0Login\0Logout\0OpenKmlFile\0fileName\0"
    "suppressMessages\0SaveScreenShot\0quality\0SetAutoPilotSpeed\0AutoPilotSpeed\0"
    "SetCamera\0camera\0speed\0SetCameraParams\0lat\0lon\0alt\0__MIDL___MIDL_itf_earthcom_0000_0000_0001\0"
    "altMode\0Range\0Tilt\0Azimuth\0SetElevationExaggeration\0ElevationExaggeration\0"
    "SetFeatureView\0feature\0ShowDescriptionBalloon\0AnimationController\0"
    "IAnimationControllerGE*\0SearchController\0ISearchControllerGE*\0"
    "StreamingProgressPercentage\0TourController\0ITourControllerGE*\0VersionAppType\0"
    "__MIDL_IApplicationGE_0001\0VersionBuild\0VersionMajor\0VersionMinor\0ViewExtents\0"
    "IViewExtentsGE*\0EnterpriseClientGE\0ProGE\0PlusGE\0FreeGE\0UnknownGE\0"
    "__MIDL_IKHInterface_0001\0GE_EC\0GE_Pro\0GE_Plus\0GE_Free\0GE_Plugin\0UNKNOWN\0"
    "__MIDL_ITimeGE_0002\0TimeNegativeInfinityGE\0TimeFiniteGE\0TimePositiveInfinityGE\0"
    "RelativeToGroundAltitudeGE\0AbsoluteAltitudeGE\0EARTHLib::IApplicationGE\0control\0"
    "EARTHLib::ICameraInfoGE\0SetAzimuth\0SetFocusPointAltitude\0FocusPointAltitude\0"
    "SetFocusPointAltitudeMode\0FocusPointAltitudeMode\0SetFocusPointLatitude\0"
    "FocusPointLatitude\0SetFocusPointLongitude\0FocusPointLongitude\0SetRange\0SetTilt\0"
    "EARTHLib::IViewExtentsGE\0East\0North\0South\0West\0EARTHLib::IFeatureGE\0GetChildren\0"
    "GetParent\0Highlight\0SetVisibility\0Visibility\0HasView\0Highlighted\0TimeInterval\0"
    "ITimeIntervalGE*\0EARTHLib::IFeatureCollectionGE\0Item\0index\0Count\0_NewEnum\0"
    "IUnknown*\0EARTHLib::ITimeIntervalGE\0BeginTime\0ITimeGE*\0EndTime\0EARTHLib::ITimeGE\0"
    "Clone\0ConvertToZone\0TimeZone\0SetDay\0Day\0SetHour\0Hour\0SetMinute\0Minute\0SetMonth\0"
    "Month\0SetSecond\0Second\0SetTimeZone\0SetType\0Type\0SetYear\0Year\0EARTHLib::IPointOnTerrainGE\0"
    "Altitude\0Latitude\0Longitude\0ProjectedOntoGlobe\0ZeroElevationExaggeration\0"
    "EARTHLib::ITourControllerGE\0PlayOrPause\0SetCycles\0Cycles\0SetPauseDelay\0"
    "PauseDelay\0Stop\0setSpeed\0EARTHLib::ISearchControllerGE\0ClearResults\0GetResults\0"
    "IsSearchInProgress\0Search\0searchString\0EARTHLib::IAnimationControllerGE\0Pause\0"
    "Play\0SetCurrentTimeInterval\0CurrentTimeInterval\0SliderTimeInterval\0"
    "EARTHLib::TimeGE\0ITimeGE\0EARTHLib::TimeIntervalGE\0ITimeIntervalGE\0"
    "EARTHLib::CameraInfoGE\0ICameraInfoGE\0EARTHLib::ViewExtentsGE\0IViewExtentsGE\0"
    "EARTHLib::TourControllerGE\0ITourControllerGE\0EARTHLib::SearchControllerGE\0"
    "ISearchControllerGE\0EARTHLib::AnimationControllerGE\0IAnimationControllerGE\0"
    "EARTHLib::FeatureGE\0IFeatureGE\0EARTHLib::FeatureCollectionGE\0IFeatureCollectionGE\0"
    "EARTHLib::PointOnTerrainGE\0IPointOnTerrainGE\0EARTHLib::KHInterface\0IKHInterface\0"
    "IKHFeature*\0LoadKml\0OpenFile\0QuitApplication\0SetRenderWindowSize\0width\0height\0"
    "currentView\0IKHViewInfo*\0terrain\0getCurrentVersion\0int&\0major\0minor\0build\0"
    "__MIDL_IKHInterface_0001&\0appType\0isClientInitialized\0setView\0view\0setViewParams\0"
    "currentViewExtents\0IKHViewExtents*\0EARTHLib::IKHInterface\0EARTHLib::IKHViewInfo\0"
    "SetLatitude\0SetLongitude\0EARTHLib::IKHViewExtents\0EARTHLib::IKHFeature\0"
    "EARTHLib::KHViewInfo\0IKHViewInfo\0EARTHLib::KHViewExtents\0IKHViewExtents\0"
    "EARTHLib::KHFeature\0IKHFeature\0"
};
#undef QT_MOC_LITERAL

static const uint qt_meta_data_EARTHLib__ApplicationGE[] = {

 // content:
    7, // revision
    0,  // classname
    1, 14, // classinfo
    27, 16, // methods
    11, 244, // properties
    4, 277, // enums/sets
    0, 0, // constructors
    0, // flags
    3, // signal count

 // classinfo: key, value
    1, 2, 

// signal: name, argc, parameters, tag, flags
    3, 4, 151, 4, 5,
    9, 1, 160, 4, 5,
    11, 3, 163, 4, 5,

// slot: name, argc, parameters, tag, flags
    14, 1, 170, 4, 9,
    17, 1, 173, 4, 9,
    20, 1, 176, 4, 9,
    22, 0, 179, 4, 9,
    23, 0, 180, 4, 9,
    25, 0, 181, 4, 9,
    26, 0, 182, 4, 9,
    27, 2, 183, 4, 9,
    31, 0, 188, 4, 9,
    32, 0, 189, 4, 9,
    33, 0, 190, 4, 9,
    34, 0, 191, 4, 9,
    35, 0, 192, 4, 9,
    36, 1, 193, 4, 9,
    39, 0, 196, 4, 9,
    40, 0, 197, 4, 9,
    41, 2, 198, 4, 9,
    44, 2, 203, 4, 9,
    46, 1, 208, 4, 9,
    48, 2, 211, 4, 9,
    51, 8, 216, 4, 9,
    60, 1, 233, 4, 9,
    62, 2, 236, 4, 9,
    64, 1, 241, 4, 9,

// signal: parameters
    QMetaType::Void, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, 5, 6, 7, 8,
    QMetaType::Void, QMetaType::QString, 10,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, QMetaType::VoidStar, 10, 12, 13,

// slot: parameters
    0x80000000 | 15, QMetaType::Int, 16,
    0x80000000 | 18, QMetaType::QString, 19,
    0x80000000 | 18, QMetaType::QString, 21,
    0x80000000 | 18,
    0x80000000 | 24,
    QMetaType::Int,
    0x80000000 | 18,
    0x80000000 | 28, QMetaType::Double, QMetaType::Double, 29, 30,
    QMetaType::Int,
    0x80000000 | 18,
    QMetaType::Void,
    QMetaType::Int,
    QMetaType::Int,
    QMetaType::Void, 0x80000000 | 37, 38,
    QMetaType::Void,
    QMetaType::Void,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, 42, 43,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, 42, 45,
    QMetaType::Void, QMetaType::Double, 47,
    QMetaType::Void, 0x80000000 | 15, QMetaType::Double, 49, 50,
    QMetaType::Void, QMetaType::Double, QMetaType::Double, QMetaType::Double, 0x80000000 | 55, QMetaType::Double, QMetaType::Double, QMetaType::Double, QMetaType::Double, 52, 53, 54, 56, 57, 58, 59, 50,
    QMetaType::Void, QMetaType::Double, 61,
    QMetaType::Void, 0x80000000 | 18, QMetaType::Double, 63, 50,
    QMetaType::Void, 0x80000000 | 18, 63,

 // properties: name, type, flags
    65, 0x80000000 | 66, 0x00005001, 		 // IAnimationControllerGE* AnimationController
    47, QMetaType::Double, 0x06015003, 		 // double AutoPilotSpeed
    61, QMetaType::Double, 0x06015003, 		 // double ElevationExaggeration
    67, 0x80000000 | 68, 0x00005001, 		 // ISearchControllerGE* SearchController
    69, QMetaType::Int, 0x02005001, 		 // int StreamingProgressPercentage
    70, 0x80000000 | 71, 0x00005001, 		 // ITourControllerGE* TourController
    72, 0x80000000 | 73, 0x02005009, 		 // __MIDL_IApplicationGE_0001 VersionAppType
    74, QMetaType::Int, 0x02005001, 		 // int VersionBuild
    75, QMetaType::Int, 0x02005001, 		 // int VersionMajor
    76, QMetaType::Int, 0x02005001, 		 // int VersionMinor
    77, 0x80000000 | 78, 0x00005001, 		 // IViewExtentsGE* ViewExtents

 // enums: name, flags, count, data
    73, 0x0, 5, 293, 
    84, 0x0, 6, 303, 
    91, 0x0, 3, 315, 
    55, 0x0, 2, 321, 

 // enum data: key, value
    79, uint(EARTHLib::EnterpriseClientGE),
    80, uint(EARTHLib::ProGE),
    81, uint(EARTHLib::PlusGE),
    82, uint(EARTHLib::FreeGE),
    83, uint(EARTHLib::UnknownGE),
    85, uint(EARTHLib::GE_EC),
    86, uint(EARTHLib::GE_Pro),
    87, uint(EARTHLib::GE_Plus),
    88, uint(EARTHLib::GE_Free),
    89, uint(EARTHLib::GE_Plugin),
    90, uint(EARTHLib::UNKNOWN),
    92, uint(EARTHLib::TimeNegativeInfinityGE),
    93, uint(EARTHLib::TimeFiniteGE),
    94, uint(EARTHLib::TimePositiveInfinityGE),
    95, uint(EARTHLib::RelativeToGroundAltitudeGE),
    96, uint(EARTHLib::AbsoluteAltitudeGE),
    0 // eod
};

ApplicationGE::ApplicationGE(QObject *parent) :
    QAxObject(parent)
{
    setControl(QStringLiteral("{8097d7e9-db9e-4aef-9b28-61d82a1df784}"));
}

const QMetaObject ApplicationGE::staticMetaObject = {
{ &QObject::staticMetaObject,
qt_meta_stringdata_all.data,
qt_meta_data_EARTHLib__ApplicationGE, nullptr, nullptr, nullptr }
};

void *ApplicationGE::qt_metacast(const char *_clname)
{
    if (!_clname) return nullptr;
    if (!strcmp(_clname, "EARTHLib::ApplicationGE"))
        return static_cast<void*>(const_cast<ApplicationGE*>(this));
    return QAxObject::qt_metacast(_clname);
}
static const uint qt_meta_data_EARTHLib__IApplicationGE[] = {

 // content:
    7, // revision
    97,  // classname
    0, 0, // classinfo
    27, 14, // methods
    12, 242, // properties
    4, 278, // enums/sets
    0, 0, // constructors
    0, // flags
    3, // signal count

// signal: name, argc, parameters, tag, flags
    3, 4, 149, 4, 5,
    9, 1, 158, 4, 5,
    11, 3, 161, 4, 5,

// slot: name, argc, parameters, tag, flags
    14, 1, 168, 4, 9,
    17, 1, 171, 4, 9,
    20, 1, 174, 4, 9,
    22, 0, 177, 4, 9,
    23, 0, 178, 4, 9,
    25, 0, 179, 4, 9,
    26, 0, 180, 4, 9,
    27, 2, 181, 4, 9,
    31, 0, 186, 4, 9,
    32, 0, 187, 4, 9,
    33, 0, 188, 4, 9,
    34, 0, 189, 4, 9,
    35, 0, 190, 4, 9,
    36, 1, 191, 4, 9,
    39, 0, 194, 4, 9,
    40, 0, 195, 4, 9,
    41, 2, 196, 4, 9,
    44, 2, 201, 4, 9,
    46, 1, 206, 4, 9,
    48, 2, 209, 4, 9,
    51, 8, 214, 4, 9,
    60, 1, 231, 4, 9,
    62, 2, 234, 4, 9,
    64, 1, 239, 4, 9,

// signal: parameters
    QMetaType::Void, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, 5, 6, 7, 8,
    QMetaType::Void, QMetaType::QString, 10,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, QMetaType::VoidStar, 10, 12, 13,

// slot: parameters
    0x80000000 | 15, QMetaType::Int, 16,
    0x80000000 | 18, QMetaType::QString, 19,
    0x80000000 | 18, QMetaType::QString, 21,
    0x80000000 | 18,
    0x80000000 | 24,
    QMetaType::Int,
    0x80000000 | 18,
    0x80000000 | 28, QMetaType::Double, QMetaType::Double, 29, 30,
    QMetaType::Int,
    0x80000000 | 18,
    QMetaType::Void,
    QMetaType::Int,
    QMetaType::Int,
    QMetaType::Void, 0x80000000 | 37, 38,
    QMetaType::Void,
    QMetaType::Void,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, 42, 43,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, 42, 45,
    QMetaType::Void, QMetaType::Double, 47,
    QMetaType::Void, 0x80000000 | 15, QMetaType::Double, 49, 50,
    QMetaType::Void, QMetaType::Double, QMetaType::Double, QMetaType::Double, 0x80000000 | 55, QMetaType::Double, QMetaType::Double, QMetaType::Double, QMetaType::Double, 52, 53, 54, 56, 57, 58, 59, 50,
    QMetaType::Void, QMetaType::Double, 61,
    QMetaType::Void, 0x80000000 | 18, QMetaType::Double, 63, 50,
    QMetaType::Void, 0x80000000 | 18, 63,

 // properties: name, type, flags
    65, 0x80000000 | 66, 0x00005001, 		 // IAnimationControllerGE* AnimationController
    47, QMetaType::Double, 0x06015003, 		 // double AutoPilotSpeed
    61, QMetaType::Double, 0x06015003, 		 // double ElevationExaggeration
    67, 0x80000000 | 68, 0x00005001, 		 // ISearchControllerGE* SearchController
    69, QMetaType::Int, 0x02005001, 		 // int StreamingProgressPercentage
    70, 0x80000000 | 71, 0x00005001, 		 // ITourControllerGE* TourController
    72, 0x80000000 | 73, 0x02005009, 		 // __MIDL_IApplicationGE_0001 VersionAppType
    74, QMetaType::Int, 0x02005001, 		 // int VersionBuild
    75, QMetaType::Int, 0x02005001, 		 // int VersionMajor
    76, QMetaType::Int, 0x02005001, 		 // int VersionMinor
    77, 0x80000000 | 78, 0x00005001, 		 // IViewExtentsGE* ViewExtents
    98, QMetaType::QString, 0x0a055003, 		 // QString control

 // enums: name, flags, count, data
    73, 0x0, 5, 294, 
    84, 0x0, 6, 304, 
    91, 0x0, 3, 316, 
    55, 0x0, 2, 322, 

 // enum data: key, value
    79, uint(EARTHLib::EnterpriseClientGE),
    80, uint(EARTHLib::ProGE),
    81, uint(EARTHLib::PlusGE),
    82, uint(EARTHLib::FreeGE),
    83, uint(EARTHLib::UnknownGE),
    85, uint(EARTHLib::GE_EC),
    86, uint(EARTHLib::GE_Pro),
    87, uint(EARTHLib::GE_Plus),
    88, uint(EARTHLib::GE_Free),
    89, uint(EARTHLib::GE_Plugin),
    90, uint(EARTHLib::UNKNOWN),
    92, uint(EARTHLib::TimeNegativeInfinityGE),
    93, uint(EARTHLib::TimeFiniteGE),
    94, uint(EARTHLib::TimePositiveInfinityGE),
    95, uint(EARTHLib::RelativeToGroundAltitudeGE),
    96, uint(EARTHLib::AbsoluteAltitudeGE),
    0 // eod
};

IApplicationGE::IApplicationGE(IDispatch *subobject, QAxObject *parent) :
    QAxObject(subobject, parent)
{
    internalRelease();
}

const QMetaObject IApplicationGE::staticMetaObject = {
{ &QObject::staticMetaObject,
qt_meta_stringdata_all.data,
qt_meta_data_EARTHLib__IApplicationGE, nullptr, nullptr, nullptr }
};

void *IApplicationGE::qt_metacast(const char *_clname)
{
    if (!_clname) return nullptr;
    if (!strcmp(_clname, "EARTHLib::IApplicationGE"))
        return static_cast<void*>(const_cast<IApplicationGE*>(this));
    return QAxObject::qt_metacast(_clname);
}
static const uint qt_meta_data_EARTHLib__ICameraInfoGE[] = {

 // content:
    7, // revision
    99,  // classname
    0, 0, // classinfo
    10, 14, // methods
    8, 104, // properties
    4, 128, // enums/sets
    0, 0, // constructors
    0, // flags
    3, // signal count

// signal: name, argc, parameters, tag, flags
    3, 4, 64, 4, 5,
    9, 1, 73, 4, 5,
    11, 3, 76, 4, 5,

// slot: name, argc, parameters, tag, flags
    100, 1, 83, 4, 9,
    101, 1, 86, 4, 9,
    103, 1, 89, 4, 9,
    105, 1, 92, 4, 9,
    107, 1, 95, 4, 9,
    109, 1, 98, 4, 9,
    110, 1, 101, 4, 9,

// signal: parameters
    QMetaType::Void, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, 5, 6, 7, 8,
    QMetaType::Void, QMetaType::QString, 10,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, QMetaType::VoidStar, 10, 12, 13,

// slot: parameters
    QMetaType::Void, QMetaType::Double, 59,
    QMetaType::Void, QMetaType::Double, 102,
    QMetaType::Void, 0x80000000 | 55, 104,
    QMetaType::Void, QMetaType::Double, 106,
    QMetaType::Void, QMetaType::Double, 108,
    QMetaType::Void, QMetaType::Double, 57,
    QMetaType::Void, QMetaType::Double, 58,

 // properties: name, type, flags
    59, QMetaType::Double, 0x06015003, 		 // double Azimuth
    102, QMetaType::Double, 0x06015003, 		 // double FocusPointAltitude
    104, 0x80000000 | 55, 0x0201500b, 		 // __MIDL___MIDL_itf_earthcom_0000_0000_0001 FocusPointAltitudeMode
    106, QMetaType::Double, 0x06015003, 		 // double FocusPointLatitude
    108, QMetaType::Double, 0x06015003, 		 // double FocusPointLongitude
    57, QMetaType::Double, 0x06015003, 		 // double Range
    58, QMetaType::Double, 0x06015003, 		 // double Tilt
    98, QMetaType::QString, 0x0a055003, 		 // QString control

 // enums: name, flags, count, data
    73, 0x0, 5, 144, 
    84, 0x0, 6, 154, 
    91, 0x0, 3, 166, 
    55, 0x0, 2, 172, 

 // enum data: key, value
    79, uint(EARTHLib::EnterpriseClientGE),
    80, uint(EARTHLib::ProGE),
    81, uint(EARTHLib::PlusGE),
    82, uint(EARTHLib::FreeGE),
    83, uint(EARTHLib::UnknownGE),
    85, uint(EARTHLib::GE_EC),
    86, uint(EARTHLib::GE_Pro),
    87, uint(EARTHLib::GE_Plus),
    88, uint(EARTHLib::GE_Free),
    89, uint(EARTHLib::GE_Plugin),
    90, uint(EARTHLib::UNKNOWN),
    92, uint(EARTHLib::TimeNegativeInfinityGE),
    93, uint(EARTHLib::TimeFiniteGE),
    94, uint(EARTHLib::TimePositiveInfinityGE),
    95, uint(EARTHLib::RelativeToGroundAltitudeGE),
    96, uint(EARTHLib::AbsoluteAltitudeGE),
    0 // eod
};

ICameraInfoGE::ICameraInfoGE(IDispatch *subobject, QAxObject *parent) :
    QAxObject(subobject, parent)
{
    internalRelease();
}

const QMetaObject ICameraInfoGE::staticMetaObject = {
{ &QObject::staticMetaObject,
qt_meta_stringdata_all.data,
qt_meta_data_EARTHLib__ICameraInfoGE, nullptr, nullptr, nullptr }
};

void *ICameraInfoGE::qt_metacast(const char *_clname)
{
    if (!_clname) return nullptr;
    if (!strcmp(_clname, "EARTHLib::ICameraInfoGE"))
        return static_cast<void*>(const_cast<ICameraInfoGE*>(this));
    return QAxObject::qt_metacast(_clname);
}
static const uint qt_meta_data_EARTHLib__IViewExtentsGE[] = {

 // content:
    7, // revision
    111,  // classname
    0, 0, // classinfo
    3, 14, // methods
    5, 48, // properties
    4, 63, // enums/sets
    0, 0, // constructors
    0, // flags
    3, // signal count

// signal: name, argc, parameters, tag, flags
    3, 4, 29, 4, 5,
    9, 1, 38, 4, 5,
    11, 3, 41, 4, 5,

// signal: parameters
    QMetaType::Void, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, 5, 6, 7, 8,
    QMetaType::Void, QMetaType::QString, 10,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, QMetaType::VoidStar, 10, 12, 13,

 // properties: name, type, flags
    112, QMetaType::Double, 0x06005001, 		 // double East
    113, QMetaType::Double, 0x06005001, 		 // double North
    114, QMetaType::Double, 0x06005001, 		 // double South
    115, QMetaType::Double, 0x06005001, 		 // double West
    98, QMetaType::QString, 0x0a055003, 		 // QString control

 // enums: name, flags, count, data
    73, 0x0, 5, 79, 
    84, 0x0, 6, 89, 
    91, 0x0, 3, 101, 
    55, 0x0, 2, 107, 

 // enum data: key, value
    79, uint(EARTHLib::EnterpriseClientGE),
    80, uint(EARTHLib::ProGE),
    81, uint(EARTHLib::PlusGE),
    82, uint(EARTHLib::FreeGE),
    83, uint(EARTHLib::UnknownGE),
    85, uint(EARTHLib::GE_EC),
    86, uint(EARTHLib::GE_Pro),
    87, uint(EARTHLib::GE_Plus),
    88, uint(EARTHLib::GE_Free),
    89, uint(EARTHLib::GE_Plugin),
    90, uint(EARTHLib::UNKNOWN),
    92, uint(EARTHLib::TimeNegativeInfinityGE),
    93, uint(EARTHLib::TimeFiniteGE),
    94, uint(EARTHLib::TimePositiveInfinityGE),
    95, uint(EARTHLib::RelativeToGroundAltitudeGE),
    96, uint(EARTHLib::AbsoluteAltitudeGE),
    0 // eod
};

IViewExtentsGE::IViewExtentsGE(IDispatch *subobject, QAxObject *parent) :
    QAxObject(subobject, parent)
{
    internalRelease();
}

const QMetaObject IViewExtentsGE::staticMetaObject = {
{ &QObject::staticMetaObject,
qt_meta_stringdata_all.data,
qt_meta_data_EARTHLib__IViewExtentsGE, nullptr, nullptr, nullptr }
};

void *IViewExtentsGE::qt_metacast(const char *_clname)
{
    if (!_clname) return nullptr;
    if (!strcmp(_clname, "EARTHLib::IViewExtentsGE"))
        return static_cast<void*>(const_cast<IViewExtentsGE*>(this));
    return QAxObject::qt_metacast(_clname);
}
static const uint qt_meta_data_EARTHLib__IFeatureGE[] = {

 // content:
    7, // revision
    116,  // classname
    0, 0, // classinfo
    7, 14, // methods
    6, 74, // properties
    4, 92, // enums/sets
    0, 0, // constructors
    0, // flags
    3, // signal count

// signal: name, argc, parameters, tag, flags
    3, 4, 49, 4, 5,
    9, 1, 58, 4, 5,
    11, 3, 61, 4, 5,

// slot: name, argc, parameters, tag, flags
    117, 0, 68, 4, 9,
    118, 0, 69, 4, 9,
    119, 0, 70, 4, 9,
    120, 1, 71, 4, 9,

// signal: parameters
    QMetaType::Void, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, 5, 6, 7, 8,
    QMetaType::Void, QMetaType::QString, 10,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, QMetaType::VoidStar, 10, 12, 13,

// slot: parameters
    0x80000000 | 24,
    0x80000000 | 18,
    QMetaType::Void,
    QMetaType::Void, QMetaType::Int, 121,

 // properties: name, type, flags
    122, QMetaType::Int, 0x02005001, 		 // int HasView
    123, QMetaType::Int, 0x02005001, 		 // int Highlighted
    21, QMetaType::QString, 0x0a005001, 		 // QString Name
    124, 0x80000000 | 125, 0x00005001, 		 // ITimeIntervalGE* TimeInterval
    121, QMetaType::Int, 0x02015003, 		 // int Visibility
    98, QMetaType::QString, 0x0a055003, 		 // QString control

 // enums: name, flags, count, data
    73, 0x0, 5, 108, 
    84, 0x0, 6, 118, 
    91, 0x0, 3, 130, 
    55, 0x0, 2, 136, 

 // enum data: key, value
    79, uint(EARTHLib::EnterpriseClientGE),
    80, uint(EARTHLib::ProGE),
    81, uint(EARTHLib::PlusGE),
    82, uint(EARTHLib::FreeGE),
    83, uint(EARTHLib::UnknownGE),
    85, uint(EARTHLib::GE_EC),
    86, uint(EARTHLib::GE_Pro),
    87, uint(EARTHLib::GE_Plus),
    88, uint(EARTHLib::GE_Free),
    89, uint(EARTHLib::GE_Plugin),
    90, uint(EARTHLib::UNKNOWN),
    92, uint(EARTHLib::TimeNegativeInfinityGE),
    93, uint(EARTHLib::TimeFiniteGE),
    94, uint(EARTHLib::TimePositiveInfinityGE),
    95, uint(EARTHLib::RelativeToGroundAltitudeGE),
    96, uint(EARTHLib::AbsoluteAltitudeGE),
    0 // eod
};

IFeatureGE::IFeatureGE(IDispatch *subobject, QAxObject *parent) :
    QAxObject(subobject, parent)
{
    internalRelease();
}

const QMetaObject IFeatureGE::staticMetaObject = {
{ &QObject::staticMetaObject,
qt_meta_stringdata_all.data,
qt_meta_data_EARTHLib__IFeatureGE, nullptr, nullptr, nullptr }
};

void *IFeatureGE::qt_metacast(const char *_clname)
{
    if (!_clname) return nullptr;
    if (!strcmp(_clname, "EARTHLib::IFeatureGE"))
        return static_cast<void*>(const_cast<IFeatureGE*>(this));
    return QAxObject::qt_metacast(_clname);
}
static const uint qt_meta_data_EARTHLib__IFeatureCollectionGE[] = {

 // content:
    7, // revision
    126,  // classname
    0, 0, // classinfo
    4, 14, // methods
    3, 56, // properties
    4, 65, // enums/sets
    0, 0, // constructors
    0, // flags
    3, // signal count

// signal: name, argc, parameters, tag, flags
    3, 4, 34, 4, 5,
    9, 1, 43, 4, 5,
    11, 3, 46, 4, 5,

// slot: name, argc, parameters, tag, flags
    127, 1, 53, 4, 9,

// signal: parameters
    QMetaType::Void, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, 5, 6, 7, 8,
    QMetaType::Void, QMetaType::QString, 10,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, QMetaType::VoidStar, 10, 12, 13,

// slot: parameters
    0x80000000 | 18, QMetaType::Int, 128,

 // properties: name, type, flags
    129, QMetaType::Int, 0x02005001, 		 // int Count
    130, 0x80000000 | 131, 0x00005001, 		 // IUnknown* _NewEnum
    98, QMetaType::QString, 0x0a055003, 		 // QString control

 // enums: name, flags, count, data
    73, 0x0, 5, 81, 
    84, 0x0, 6, 91, 
    91, 0x0, 3, 103, 
    55, 0x0, 2, 109, 

 // enum data: key, value
    79, uint(EARTHLib::EnterpriseClientGE),
    80, uint(EARTHLib::ProGE),
    81, uint(EARTHLib::PlusGE),
    82, uint(EARTHLib::FreeGE),
    83, uint(EARTHLib::UnknownGE),
    85, uint(EARTHLib::GE_EC),
    86, uint(EARTHLib::GE_Pro),
    87, uint(EARTHLib::GE_Plus),
    88, uint(EARTHLib::GE_Free),
    89, uint(EARTHLib::GE_Plugin),
    90, uint(EARTHLib::UNKNOWN),
    92, uint(EARTHLib::TimeNegativeInfinityGE),
    93, uint(EARTHLib::TimeFiniteGE),
    94, uint(EARTHLib::TimePositiveInfinityGE),
    95, uint(EARTHLib::RelativeToGroundAltitudeGE),
    96, uint(EARTHLib::AbsoluteAltitudeGE),
    0 // eod
};

IFeatureCollectionGE::IFeatureCollectionGE(IDispatch *subobject, QAxObject *parent) :
    QAxObject(subobject, parent)
{
    internalRelease();
}

const QMetaObject IFeatureCollectionGE::staticMetaObject = {
{ &QObject::staticMetaObject,
qt_meta_stringdata_all.data,
qt_meta_data_EARTHLib__IFeatureCollectionGE, nullptr, nullptr, nullptr }
};

void *IFeatureCollectionGE::qt_metacast(const char *_clname)
{
    if (!_clname) return nullptr;
    if (!strcmp(_clname, "EARTHLib::IFeatureCollectionGE"))
        return static_cast<void*>(const_cast<IFeatureCollectionGE*>(this));
    return QAxObject::qt_metacast(_clname);
}
static const uint qt_meta_data_EARTHLib__ITimeIntervalGE[] = {

 // content:
    7, // revision
    132,  // classname
    0, 0, // classinfo
    3, 14, // methods
    3, 48, // properties
    4, 57, // enums/sets
    0, 0, // constructors
    0, // flags
    3, // signal count

// signal: name, argc, parameters, tag, flags
    3, 4, 29, 4, 5,
    9, 1, 38, 4, 5,
    11, 3, 41, 4, 5,

// signal: parameters
    QMetaType::Void, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, 5, 6, 7, 8,
    QMetaType::Void, QMetaType::QString, 10,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, QMetaType::VoidStar, 10, 12, 13,

 // properties: name, type, flags
    133, 0x80000000 | 134, 0x00005001, 		 // ITimeGE* BeginTime
    135, 0x80000000 | 134, 0x00005001, 		 // ITimeGE* EndTime
    98, QMetaType::QString, 0x0a055003, 		 // QString control

 // enums: name, flags, count, data
    73, 0x0, 5, 73, 
    84, 0x0, 6, 83, 
    91, 0x0, 3, 95, 
    55, 0x0, 2, 101, 

 // enum data: key, value
    79, uint(EARTHLib::EnterpriseClientGE),
    80, uint(EARTHLib::ProGE),
    81, uint(EARTHLib::PlusGE),
    82, uint(EARTHLib::FreeGE),
    83, uint(EARTHLib::UnknownGE),
    85, uint(EARTHLib::GE_EC),
    86, uint(EARTHLib::GE_Pro),
    87, uint(EARTHLib::GE_Plus),
    88, uint(EARTHLib::GE_Free),
    89, uint(EARTHLib::GE_Plugin),
    90, uint(EARTHLib::UNKNOWN),
    92, uint(EARTHLib::TimeNegativeInfinityGE),
    93, uint(EARTHLib::TimeFiniteGE),
    94, uint(EARTHLib::TimePositiveInfinityGE),
    95, uint(EARTHLib::RelativeToGroundAltitudeGE),
    96, uint(EARTHLib::AbsoluteAltitudeGE),
    0 // eod
};

ITimeIntervalGE::ITimeIntervalGE(IDispatch *subobject, QAxObject *parent) :
    QAxObject(subobject, parent)
{
    internalRelease();
}

const QMetaObject ITimeIntervalGE::staticMetaObject = {
{ &QObject::staticMetaObject,
qt_meta_stringdata_all.data,
qt_meta_data_EARTHLib__ITimeIntervalGE, nullptr, nullptr, nullptr }
};

void *ITimeIntervalGE::qt_metacast(const char *_clname)
{
    if (!_clname) return nullptr;
    if (!strcmp(_clname, "EARTHLib::ITimeIntervalGE"))
        return static_cast<void*>(const_cast<ITimeIntervalGE*>(this));
    return QAxObject::qt_metacast(_clname);
}
static const uint qt_meta_data_EARTHLib__ITimeGE[] = {

 // content:
    7, // revision
    136,  // classname
    0, 0, // classinfo
    13, 14, // methods
    9, 126, // properties
    4, 153, // enums/sets
    0, 0, // constructors
    0, // flags
    3, // signal count

// signal: name, argc, parameters, tag, flags
    3, 4, 79, 4, 5,
    9, 1, 88, 4, 5,
    11, 3, 91, 4, 5,

// slot: name, argc, parameters, tag, flags
    137, 0, 98, 4, 9,
    138, 1, 99, 4, 9,
    140, 1, 102, 4, 9,
    142, 1, 105, 4, 9,
    144, 1, 108, 4, 9,
    146, 1, 111, 4, 9,
    148, 1, 114, 4, 9,
    150, 1, 117, 4, 9,
    151, 1, 120, 4, 9,
    153, 1, 123, 4, 9,

// signal: parameters
    QMetaType::Void, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, 5, 6, 7, 8,
    QMetaType::Void, QMetaType::QString, 10,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, QMetaType::VoidStar, 10, 12, 13,

// slot: parameters
    0x80000000 | 134,
    0x80000000 | 134, QMetaType::Double, 139,
    QMetaType::Void, QMetaType::Int, 141,
    QMetaType::Void, QMetaType::Int, 143,
    QMetaType::Void, QMetaType::Int, 145,
    QMetaType::Void, QMetaType::Int, 147,
    QMetaType::Void, QMetaType::Int, 149,
    QMetaType::Void, QMetaType::Double, 139,
    QMetaType::Void, 0x80000000 | 91, 152,
    QMetaType::Void, QMetaType::Int, 154,

 // properties: name, type, flags
    141, QMetaType::Int, 0x02015003, 		 // int Day
    143, QMetaType::Int, 0x02015003, 		 // int Hour
    145, QMetaType::Int, 0x02015003, 		 // int Minute
    147, QMetaType::Int, 0x02015003, 		 // int Month
    149, QMetaType::Int, 0x02015003, 		 // int Second
    139, QMetaType::Double, 0x06015003, 		 // double TimeZone
    152, 0x80000000 | 91, 0x0201500b, 		 // __MIDL_ITimeGE_0002 Type
    154, QMetaType::Int, 0x02015003, 		 // int Year
    98, QMetaType::QString, 0x0a055003, 		 // QString control

 // enums: name, flags, count, data
    73, 0x0, 5, 169, 
    84, 0x0, 6, 179, 
    91, 0x0, 3, 191, 
    55, 0x0, 2, 197, 

 // enum data: key, value
    79, uint(EARTHLib::EnterpriseClientGE),
    80, uint(EARTHLib::ProGE),
    81, uint(EARTHLib::PlusGE),
    82, uint(EARTHLib::FreeGE),
    83, uint(EARTHLib::UnknownGE),
    85, uint(EARTHLib::GE_EC),
    86, uint(EARTHLib::GE_Pro),
    87, uint(EARTHLib::GE_Plus),
    88, uint(EARTHLib::GE_Free),
    89, uint(EARTHLib::GE_Plugin),
    90, uint(EARTHLib::UNKNOWN),
    92, uint(EARTHLib::TimeNegativeInfinityGE),
    93, uint(EARTHLib::TimeFiniteGE),
    94, uint(EARTHLib::TimePositiveInfinityGE),
    95, uint(EARTHLib::RelativeToGroundAltitudeGE),
    96, uint(EARTHLib::AbsoluteAltitudeGE),
    0 // eod
};

ITimeGE::ITimeGE(IDispatch *subobject, QAxObject *parent) :
    QAxObject(subobject, parent)
{
    internalRelease();
}

const QMetaObject ITimeGE::staticMetaObject = {
{ &QObject::staticMetaObject,
qt_meta_stringdata_all.data,
qt_meta_data_EARTHLib__ITimeGE, nullptr, nullptr, nullptr }
};

void *ITimeGE::qt_metacast(const char *_clname)
{
    if (!_clname) return nullptr;
    if (!strcmp(_clname, "EARTHLib::ITimeGE"))
        return static_cast<void*>(const_cast<ITimeGE*>(this));
    return QAxObject::qt_metacast(_clname);
}
static const uint qt_meta_data_EARTHLib__IPointOnTerrainGE[] = {

 // content:
    7, // revision
    155,  // classname
    0, 0, // classinfo
    3, 14, // methods
    6, 48, // properties
    4, 66, // enums/sets
    0, 0, // constructors
    0, // flags
    3, // signal count

// signal: name, argc, parameters, tag, flags
    3, 4, 29, 4, 5,
    9, 1, 38, 4, 5,
    11, 3, 41, 4, 5,

// signal: parameters
    QMetaType::Void, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, 5, 6, 7, 8,
    QMetaType::Void, QMetaType::QString, 10,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, QMetaType::VoidStar, 10, 12, 13,

 // properties: name, type, flags
    156, QMetaType::Double, 0x06005001, 		 // double Altitude
    157, QMetaType::Double, 0x06005001, 		 // double Latitude
    158, QMetaType::Double, 0x06005001, 		 // double Longitude
    159, QMetaType::Int, 0x02005001, 		 // int ProjectedOntoGlobe
    160, QMetaType::Int, 0x02005001, 		 // int ZeroElevationExaggeration
    98, QMetaType::QString, 0x0a055003, 		 // QString control

 // enums: name, flags, count, data
    73, 0x0, 5, 82, 
    84, 0x0, 6, 92, 
    91, 0x0, 3, 104, 
    55, 0x0, 2, 110, 

 // enum data: key, value
    79, uint(EARTHLib::EnterpriseClientGE),
    80, uint(EARTHLib::ProGE),
    81, uint(EARTHLib::PlusGE),
    82, uint(EARTHLib::FreeGE),
    83, uint(EARTHLib::UnknownGE),
    85, uint(EARTHLib::GE_EC),
    86, uint(EARTHLib::GE_Pro),
    87, uint(EARTHLib::GE_Plus),
    88, uint(EARTHLib::GE_Free),
    89, uint(EARTHLib::GE_Plugin),
    90, uint(EARTHLib::UNKNOWN),
    92, uint(EARTHLib::TimeNegativeInfinityGE),
    93, uint(EARTHLib::TimeFiniteGE),
    94, uint(EARTHLib::TimePositiveInfinityGE),
    95, uint(EARTHLib::RelativeToGroundAltitudeGE),
    96, uint(EARTHLib::AbsoluteAltitudeGE),
    0 // eod
};

IPointOnTerrainGE::IPointOnTerrainGE(IDispatch *subobject, QAxObject *parent) :
    QAxObject(subobject, parent)
{
    internalRelease();
}

const QMetaObject IPointOnTerrainGE::staticMetaObject = {
{ &QObject::staticMetaObject,
qt_meta_stringdata_all.data,
qt_meta_data_EARTHLib__IPointOnTerrainGE, nullptr, nullptr, nullptr }
};

void *IPointOnTerrainGE::qt_metacast(const char *_clname)
{
    if (!_clname) return nullptr;
    if (!strcmp(_clname, "EARTHLib::IPointOnTerrainGE"))
        return static_cast<void*>(const_cast<IPointOnTerrainGE*>(this));
    return QAxObject::qt_metacast(_clname);
}
static const uint qt_meta_data_EARTHLib__ITourControllerGE[] = {

 // content:
    7, // revision
    161,  // classname
    0, 0, // classinfo
    8, 14, // methods
    4, 84, // properties
    4, 96, // enums/sets
    0, 0, // constructors
    0, // flags
    3, // signal count

// signal: name, argc, parameters, tag, flags
    3, 4, 54, 4, 5,
    9, 1, 63, 4, 5,
    11, 3, 66, 4, 5,

// slot: name, argc, parameters, tag, flags
    162, 0, 73, 4, 9,
    163, 1, 74, 4, 9,
    165, 1, 77, 4, 9,
    167, 0, 80, 4, 9,
    168, 1, 81, 4, 9,

// signal: parameters
    QMetaType::Void, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, 5, 6, 7, 8,
    QMetaType::Void, QMetaType::QString, 10,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, QMetaType::VoidStar, 10, 12, 13,

// slot: parameters
    QMetaType::Void,
    QMetaType::Void, QMetaType::Int, 164,
    QMetaType::Void, QMetaType::Double, 166,
    QMetaType::Void,
    QMetaType::Void, QMetaType::Double, 50,

 // properties: name, type, flags
    164, QMetaType::Int, 0x02015003, 		 // int Cycles
    166, QMetaType::Double, 0x06015003, 		 // double PauseDelay
    98, QMetaType::QString, 0x0a055003, 		 // QString control
    50, QMetaType::Double, 0x06015003, 		 // double speed

 // enums: name, flags, count, data
    73, 0x0, 5, 112, 
    84, 0x0, 6, 122, 
    91, 0x0, 3, 134, 
    55, 0x0, 2, 140, 

 // enum data: key, value
    79, uint(EARTHLib::EnterpriseClientGE),
    80, uint(EARTHLib::ProGE),
    81, uint(EARTHLib::PlusGE),
    82, uint(EARTHLib::FreeGE),
    83, uint(EARTHLib::UnknownGE),
    85, uint(EARTHLib::GE_EC),
    86, uint(EARTHLib::GE_Pro),
    87, uint(EARTHLib::GE_Plus),
    88, uint(EARTHLib::GE_Free),
    89, uint(EARTHLib::GE_Plugin),
    90, uint(EARTHLib::UNKNOWN),
    92, uint(EARTHLib::TimeNegativeInfinityGE),
    93, uint(EARTHLib::TimeFiniteGE),
    94, uint(EARTHLib::TimePositiveInfinityGE),
    95, uint(EARTHLib::RelativeToGroundAltitudeGE),
    96, uint(EARTHLib::AbsoluteAltitudeGE),
    0 // eod
};

ITourControllerGE::ITourControllerGE(IDispatch *subobject, QAxObject *parent) :
    QAxObject(subobject, parent)
{
    internalRelease();
}

const QMetaObject ITourControllerGE::staticMetaObject = {
{ &QObject::staticMetaObject,
qt_meta_stringdata_all.data,
qt_meta_data_EARTHLib__ITourControllerGE, nullptr, nullptr, nullptr }
};

void *ITourControllerGE::qt_metacast(const char *_clname)
{
    if (!_clname) return nullptr;
    if (!strcmp(_clname, "EARTHLib::ITourControllerGE"))
        return static_cast<void*>(const_cast<ITourControllerGE*>(this));
    return QAxObject::qt_metacast(_clname);
}
static const uint qt_meta_data_EARTHLib__ISearchControllerGE[] = {

 // content:
    7, // revision
    169,  // classname
    0, 0, // classinfo
    7, 14, // methods
    1, 74, // properties
    4, 77, // enums/sets
    0, 0, // constructors
    0, // flags
    3, // signal count

// signal: name, argc, parameters, tag, flags
    3, 4, 49, 4, 5,
    9, 1, 58, 4, 5,
    11, 3, 61, 4, 5,

// slot: name, argc, parameters, tag, flags
    170, 0, 68, 4, 9,
    171, 0, 69, 4, 9,
    172, 0, 70, 4, 9,
    173, 1, 71, 4, 9,

// signal: parameters
    QMetaType::Void, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, 5, 6, 7, 8,
    QMetaType::Void, QMetaType::QString, 10,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, QMetaType::VoidStar, 10, 12, 13,

// slot: parameters
    QMetaType::Void,
    0x80000000 | 24,
    QMetaType::Int,
    QMetaType::Void, QMetaType::QString, 174,

 // properties: name, type, flags
    98, QMetaType::QString, 0x0a055003, 		 // QString control

 // enums: name, flags, count, data
    73, 0x0, 5, 93, 
    84, 0x0, 6, 103, 
    91, 0x0, 3, 115, 
    55, 0x0, 2, 121, 

 // enum data: key, value
    79, uint(EARTHLib::EnterpriseClientGE),
    80, uint(EARTHLib::ProGE),
    81, uint(EARTHLib::PlusGE),
    82, uint(EARTHLib::FreeGE),
    83, uint(EARTHLib::UnknownGE),
    85, uint(EARTHLib::GE_EC),
    86, uint(EARTHLib::GE_Pro),
    87, uint(EARTHLib::GE_Plus),
    88, uint(EARTHLib::GE_Free),
    89, uint(EARTHLib::GE_Plugin),
    90, uint(EARTHLib::UNKNOWN),
    92, uint(EARTHLib::TimeNegativeInfinityGE),
    93, uint(EARTHLib::TimeFiniteGE),
    94, uint(EARTHLib::TimePositiveInfinityGE),
    95, uint(EARTHLib::RelativeToGroundAltitudeGE),
    96, uint(EARTHLib::AbsoluteAltitudeGE),
    0 // eod
};

ISearchControllerGE::ISearchControllerGE(IDispatch *subobject, QAxObject *parent) :
    QAxObject(subobject, parent)
{
    internalRelease();
}

const QMetaObject ISearchControllerGE::staticMetaObject = {
{ &QObject::staticMetaObject,
qt_meta_stringdata_all.data,
qt_meta_data_EARTHLib__ISearchControllerGE, nullptr, nullptr, nullptr }
};

void *ISearchControllerGE::qt_metacast(const char *_clname)
{
    if (!_clname) return nullptr;
    if (!strcmp(_clname, "EARTHLib::ISearchControllerGE"))
        return static_cast<void*>(const_cast<ISearchControllerGE*>(this));
    return QAxObject::qt_metacast(_clname);
}
static const uint qt_meta_data_EARTHLib__IAnimationControllerGE[] = {

 // content:
    7, // revision
    175,  // classname
    0, 0, // classinfo
    6, 14, // methods
    3, 68, // properties
    4, 77, // enums/sets
    0, 0, // constructors
    0, // flags
    3, // signal count

// signal: name, argc, parameters, tag, flags
    3, 4, 44, 4, 5,
    9, 1, 53, 4, 5,
    11, 3, 56, 4, 5,

// slot: name, argc, parameters, tag, flags
    176, 0, 63, 4, 9,
    177, 0, 64, 4, 9,
    178, 1, 65, 4, 9,

// signal: parameters
    QMetaType::Void, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, 5, 6, 7, 8,
    QMetaType::Void, QMetaType::QString, 10,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, QMetaType::VoidStar, 10, 12, 13,

// slot: parameters
    QMetaType::Void,
    QMetaType::Void,
    QMetaType::Void, 0x80000000 | 125, 179,

 // properties: name, type, flags
    179, 0x80000000 | 125, 0x00015003, 		 // ITimeIntervalGE* CurrentTimeInterval
    180, 0x80000000 | 125, 0x00005001, 		 // ITimeIntervalGE* SliderTimeInterval
    98, QMetaType::QString, 0x0a055003, 		 // QString control

 // enums: name, flags, count, data
    73, 0x0, 5, 93, 
    84, 0x0, 6, 103, 
    91, 0x0, 3, 115, 
    55, 0x0, 2, 121, 

 // enum data: key, value
    79, uint(EARTHLib::EnterpriseClientGE),
    80, uint(EARTHLib::ProGE),
    81, uint(EARTHLib::PlusGE),
    82, uint(EARTHLib::FreeGE),
    83, uint(EARTHLib::UnknownGE),
    85, uint(EARTHLib::GE_EC),
    86, uint(EARTHLib::GE_Pro),
    87, uint(EARTHLib::GE_Plus),
    88, uint(EARTHLib::GE_Free),
    89, uint(EARTHLib::GE_Plugin),
    90, uint(EARTHLib::UNKNOWN),
    92, uint(EARTHLib::TimeNegativeInfinityGE),
    93, uint(EARTHLib::TimeFiniteGE),
    94, uint(EARTHLib::TimePositiveInfinityGE),
    95, uint(EARTHLib::RelativeToGroundAltitudeGE),
    96, uint(EARTHLib::AbsoluteAltitudeGE),
    0 // eod
};

IAnimationControllerGE::IAnimationControllerGE(IDispatch *subobject, QAxObject *parent) :
    QAxObject(subobject, parent)
{
    internalRelease();
}

const QMetaObject IAnimationControllerGE::staticMetaObject = {
{ &QObject::staticMetaObject,
qt_meta_stringdata_all.data,
qt_meta_data_EARTHLib__IAnimationControllerGE, nullptr, nullptr, nullptr }
};

void *IAnimationControllerGE::qt_metacast(const char *_clname)
{
    if (!_clname) return nullptr;
    if (!strcmp(_clname, "EARTHLib::IAnimationControllerGE"))
        return static_cast<void*>(const_cast<IAnimationControllerGE*>(this));
    return QAxObject::qt_metacast(_clname);
}
static const uint qt_meta_data_EARTHLib__TimeGE[] = {

 // content:
    7, // revision
    181,  // classname
    1, 14, // classinfo
    13, 16, // methods
    8, 128, // properties
    4, 152, // enums/sets
    0, 0, // constructors
    0, // flags
    3, // signal count

 // classinfo: key, value
    1, 182, 

// signal: name, argc, parameters, tag, flags
    3, 4, 81, 4, 5,
    9, 1, 90, 4, 5,
    11, 3, 93, 4, 5,

// slot: name, argc, parameters, tag, flags
    137, 0, 100, 4, 9,
    138, 1, 101, 4, 9,
    140, 1, 104, 4, 9,
    142, 1, 107, 4, 9,
    144, 1, 110, 4, 9,
    146, 1, 113, 4, 9,
    148, 1, 116, 4, 9,
    150, 1, 119, 4, 9,
    151, 1, 122, 4, 9,
    153, 1, 125, 4, 9,

// signal: parameters
    QMetaType::Void, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, 5, 6, 7, 8,
    QMetaType::Void, QMetaType::QString, 10,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, QMetaType::VoidStar, 10, 12, 13,

// slot: parameters
    0x80000000 | 134,
    0x80000000 | 134, QMetaType::Double, 139,
    QMetaType::Void, QMetaType::Int, 141,
    QMetaType::Void, QMetaType::Int, 143,
    QMetaType::Void, QMetaType::Int, 145,
    QMetaType::Void, QMetaType::Int, 147,
    QMetaType::Void, QMetaType::Int, 149,
    QMetaType::Void, QMetaType::Double, 139,
    QMetaType::Void, 0x80000000 | 91, 152,
    QMetaType::Void, QMetaType::Int, 154,

 // properties: name, type, flags
    141, QMetaType::Int, 0x02015003, 		 // int Day
    143, QMetaType::Int, 0x02015003, 		 // int Hour
    145, QMetaType::Int, 0x02015003, 		 // int Minute
    147, QMetaType::Int, 0x02015003, 		 // int Month
    149, QMetaType::Int, 0x02015003, 		 // int Second
    139, QMetaType::Double, 0x06015003, 		 // double TimeZone
    152, 0x80000000 | 91, 0x0201500b, 		 // __MIDL_ITimeGE_0002 Type
    154, QMetaType::Int, 0x02015003, 		 // int Year

 // enums: name, flags, count, data
    73, 0x0, 5, 168, 
    84, 0x0, 6, 178, 
    91, 0x0, 3, 190, 
    55, 0x0, 2, 196, 

 // enum data: key, value
    79, uint(EARTHLib::EnterpriseClientGE),
    80, uint(EARTHLib::ProGE),
    81, uint(EARTHLib::PlusGE),
    82, uint(EARTHLib::FreeGE),
    83, uint(EARTHLib::UnknownGE),
    85, uint(EARTHLib::GE_EC),
    86, uint(EARTHLib::GE_Pro),
    87, uint(EARTHLib::GE_Plus),
    88, uint(EARTHLib::GE_Free),
    89, uint(EARTHLib::GE_Plugin),
    90, uint(EARTHLib::UNKNOWN),
    92, uint(EARTHLib::TimeNegativeInfinityGE),
    93, uint(EARTHLib::TimeFiniteGE),
    94, uint(EARTHLib::TimePositiveInfinityGE),
    95, uint(EARTHLib::RelativeToGroundAltitudeGE),
    96, uint(EARTHLib::AbsoluteAltitudeGE),
    0 // eod
};

TimeGE::TimeGE(QObject *parent) :
    QAxObject(parent)
{
    setControl(QStringLiteral("{1aedb68d-18a7-4ca9-b41b-3ce7e59fab24}"));
}

const QMetaObject TimeGE::staticMetaObject = {
{ &QObject::staticMetaObject,
qt_meta_stringdata_all.data,
qt_meta_data_EARTHLib__TimeGE, nullptr, nullptr, nullptr }
};

void *TimeGE::qt_metacast(const char *_clname)
{
    if (!_clname) return nullptr;
    if (!strcmp(_clname, "EARTHLib::TimeGE"))
        return static_cast<void*>(const_cast<TimeGE*>(this));
    return QAxObject::qt_metacast(_clname);
}
static const uint qt_meta_data_EARTHLib__TimeIntervalGE[] = {

 // content:
    7, // revision
    183,  // classname
    1, 14, // classinfo
    3, 16, // methods
    2, 50, // properties
    4, 56, // enums/sets
    0, 0, // constructors
    0, // flags
    3, // signal count

 // classinfo: key, value
    1, 184, 

// signal: name, argc, parameters, tag, flags
    3, 4, 31, 4, 5,
    9, 1, 40, 4, 5,
    11, 3, 43, 4, 5,

// signal: parameters
    QMetaType::Void, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, 5, 6, 7, 8,
    QMetaType::Void, QMetaType::QString, 10,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, QMetaType::VoidStar, 10, 12, 13,

 // properties: name, type, flags
    133, 0x80000000 | 134, 0x00005001, 		 // ITimeGE* BeginTime
    135, 0x80000000 | 134, 0x00005001, 		 // ITimeGE* EndTime

 // enums: name, flags, count, data
    73, 0x0, 5, 72, 
    84, 0x0, 6, 82, 
    91, 0x0, 3, 94, 
    55, 0x0, 2, 100, 

 // enum data: key, value
    79, uint(EARTHLib::EnterpriseClientGE),
    80, uint(EARTHLib::ProGE),
    81, uint(EARTHLib::PlusGE),
    82, uint(EARTHLib::FreeGE),
    83, uint(EARTHLib::UnknownGE),
    85, uint(EARTHLib::GE_EC),
    86, uint(EARTHLib::GE_Pro),
    87, uint(EARTHLib::GE_Plus),
    88, uint(EARTHLib::GE_Free),
    89, uint(EARTHLib::GE_Plugin),
    90, uint(EARTHLib::UNKNOWN),
    92, uint(EARTHLib::TimeNegativeInfinityGE),
    93, uint(EARTHLib::TimeFiniteGE),
    94, uint(EARTHLib::TimePositiveInfinityGE),
    95, uint(EARTHLib::RelativeToGroundAltitudeGE),
    96, uint(EARTHLib::AbsoluteAltitudeGE),
    0 // eod
};

TimeIntervalGE::TimeIntervalGE(QObject *parent) :
    QAxObject(parent)
{
    setControl(QStringLiteral("{42df0d46-7d49-4ae5-8ef6-9ca6e41efec1}"));
}

const QMetaObject TimeIntervalGE::staticMetaObject = {
{ &QObject::staticMetaObject,
qt_meta_stringdata_all.data,
qt_meta_data_EARTHLib__TimeIntervalGE, nullptr, nullptr, nullptr }
};

void *TimeIntervalGE::qt_metacast(const char *_clname)
{
    if (!_clname) return nullptr;
    if (!strcmp(_clname, "EARTHLib::TimeIntervalGE"))
        return static_cast<void*>(const_cast<TimeIntervalGE*>(this));
    return QAxObject::qt_metacast(_clname);
}
static const uint qt_meta_data_EARTHLib__CameraInfoGE[] = {

 // content:
    7, // revision
    185,  // classname
    1, 14, // classinfo
    10, 16, // methods
    7, 106, // properties
    4, 127, // enums/sets
    0, 0, // constructors
    0, // flags
    3, // signal count

 // classinfo: key, value
    1, 186, 

// signal: name, argc, parameters, tag, flags
    3, 4, 66, 4, 5,
    9, 1, 75, 4, 5,
    11, 3, 78, 4, 5,

// slot: name, argc, parameters, tag, flags
    100, 1, 85, 4, 9,
    101, 1, 88, 4, 9,
    103, 1, 91, 4, 9,
    105, 1, 94, 4, 9,
    107, 1, 97, 4, 9,
    109, 1, 100, 4, 9,
    110, 1, 103, 4, 9,

// signal: parameters
    QMetaType::Void, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, 5, 6, 7, 8,
    QMetaType::Void, QMetaType::QString, 10,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, QMetaType::VoidStar, 10, 12, 13,

// slot: parameters
    QMetaType::Void, QMetaType::Double, 59,
    QMetaType::Void, QMetaType::Double, 102,
    QMetaType::Void, 0x80000000 | 55, 104,
    QMetaType::Void, QMetaType::Double, 106,
    QMetaType::Void, QMetaType::Double, 108,
    QMetaType::Void, QMetaType::Double, 57,
    QMetaType::Void, QMetaType::Double, 58,

 // properties: name, type, flags
    59, QMetaType::Double, 0x06015003, 		 // double Azimuth
    102, QMetaType::Double, 0x06015003, 		 // double FocusPointAltitude
    104, 0x80000000 | 55, 0x0201500b, 		 // __MIDL___MIDL_itf_earthcom_0000_0000_0001 FocusPointAltitudeMode
    106, QMetaType::Double, 0x06015003, 		 // double FocusPointLatitude
    108, QMetaType::Double, 0x06015003, 		 // double FocusPointLongitude
    57, QMetaType::Double, 0x06015003, 		 // double Range
    58, QMetaType::Double, 0x06015003, 		 // double Tilt

 // enums: name, flags, count, data
    73, 0x0, 5, 143, 
    84, 0x0, 6, 153, 
    91, 0x0, 3, 165, 
    55, 0x0, 2, 171, 

 // enum data: key, value
    79, uint(EARTHLib::EnterpriseClientGE),
    80, uint(EARTHLib::ProGE),
    81, uint(EARTHLib::PlusGE),
    82, uint(EARTHLib::FreeGE),
    83, uint(EARTHLib::UnknownGE),
    85, uint(EARTHLib::GE_EC),
    86, uint(EARTHLib::GE_Pro),
    87, uint(EARTHLib::GE_Plus),
    88, uint(EARTHLib::GE_Free),
    89, uint(EARTHLib::GE_Plugin),
    90, uint(EARTHLib::UNKNOWN),
    92, uint(EARTHLib::TimeNegativeInfinityGE),
    93, uint(EARTHLib::TimeFiniteGE),
    94, uint(EARTHLib::TimePositiveInfinityGE),
    95, uint(EARTHLib::RelativeToGroundAltitudeGE),
    96, uint(EARTHLib::AbsoluteAltitudeGE),
    0 // eod
};

CameraInfoGE::CameraInfoGE(QObject *parent) :
    QAxObject(parent)
{
    setControl(QStringLiteral("{645eee5a-bd51-4c05-a6af-6f2cf8950aab}"));
}

const QMetaObject CameraInfoGE::staticMetaObject = {
{ &QObject::staticMetaObject,
qt_meta_stringdata_all.data,
qt_meta_data_EARTHLib__CameraInfoGE, nullptr, nullptr, nullptr }
};

void *CameraInfoGE::qt_metacast(const char *_clname)
{
    if (!_clname) return nullptr;
    if (!strcmp(_clname, "EARTHLib::CameraInfoGE"))
        return static_cast<void*>(const_cast<CameraInfoGE*>(this));
    return QAxObject::qt_metacast(_clname);
}
static const uint qt_meta_data_EARTHLib__ViewExtentsGE[] = {

 // content:
    7, // revision
    187,  // classname
    1, 14, // classinfo
    3, 16, // methods
    4, 50, // properties
    4, 62, // enums/sets
    0, 0, // constructors
    0, // flags
    3, // signal count

 // classinfo: key, value
    1, 188, 

// signal: name, argc, parameters, tag, flags
    3, 4, 31, 4, 5,
    9, 1, 40, 4, 5,
    11, 3, 43, 4, 5,

// signal: parameters
    QMetaType::Void, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, 5, 6, 7, 8,
    QMetaType::Void, QMetaType::QString, 10,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, QMetaType::VoidStar, 10, 12, 13,

 // properties: name, type, flags
    112, QMetaType::Double, 0x06005001, 		 // double East
    113, QMetaType::Double, 0x06005001, 		 // double North
    114, QMetaType::Double, 0x06005001, 		 // double South
    115, QMetaType::Double, 0x06005001, 		 // double West

 // enums: name, flags, count, data
    73, 0x0, 5, 78, 
    84, 0x0, 6, 88, 
    91, 0x0, 3, 100, 
    55, 0x0, 2, 106, 

 // enum data: key, value
    79, uint(EARTHLib::EnterpriseClientGE),
    80, uint(EARTHLib::ProGE),
    81, uint(EARTHLib::PlusGE),
    82, uint(EARTHLib::FreeGE),
    83, uint(EARTHLib::UnknownGE),
    85, uint(EARTHLib::GE_EC),
    86, uint(EARTHLib::GE_Pro),
    87, uint(EARTHLib::GE_Plus),
    88, uint(EARTHLib::GE_Free),
    89, uint(EARTHLib::GE_Plugin),
    90, uint(EARTHLib::UNKNOWN),
    92, uint(EARTHLib::TimeNegativeInfinityGE),
    93, uint(EARTHLib::TimeFiniteGE),
    94, uint(EARTHLib::TimePositiveInfinityGE),
    95, uint(EARTHLib::RelativeToGroundAltitudeGE),
    96, uint(EARTHLib::AbsoluteAltitudeGE),
    0 // eod
};

ViewExtentsGE::ViewExtentsGE(QObject *parent) :
    QAxObject(parent)
{
    setControl(QStringLiteral("{d93bf052-fc68-4db6-a4f8-a4dc9beeb1c0}"));
}

const QMetaObject ViewExtentsGE::staticMetaObject = {
{ &QObject::staticMetaObject,
qt_meta_stringdata_all.data,
qt_meta_data_EARTHLib__ViewExtentsGE, nullptr, nullptr, nullptr }
};

void *ViewExtentsGE::qt_metacast(const char *_clname)
{
    if (!_clname) return nullptr;
    if (!strcmp(_clname, "EARTHLib::ViewExtentsGE"))
        return static_cast<void*>(const_cast<ViewExtentsGE*>(this));
    return QAxObject::qt_metacast(_clname);
}
static const uint qt_meta_data_EARTHLib__TourControllerGE[] = {

 // content:
    7, // revision
    189,  // classname
    1, 14, // classinfo
    8, 16, // methods
    3, 86, // properties
    4, 95, // enums/sets
    0, 0, // constructors
    0, // flags
    3, // signal count

 // classinfo: key, value
    1, 190, 

// signal: name, argc, parameters, tag, flags
    3, 4, 56, 4, 5,
    9, 1, 65, 4, 5,
    11, 3, 68, 4, 5,

// slot: name, argc, parameters, tag, flags
    162, 0, 75, 4, 9,
    163, 1, 76, 4, 9,
    165, 1, 79, 4, 9,
    167, 0, 82, 4, 9,
    168, 1, 83, 4, 9,

// signal: parameters
    QMetaType::Void, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, 5, 6, 7, 8,
    QMetaType::Void, QMetaType::QString, 10,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, QMetaType::VoidStar, 10, 12, 13,

// slot: parameters
    QMetaType::Void,
    QMetaType::Void, QMetaType::Int, 164,
    QMetaType::Void, QMetaType::Double, 166,
    QMetaType::Void,
    QMetaType::Void, QMetaType::Double, 50,

 // properties: name, type, flags
    164, QMetaType::Int, 0x02015003, 		 // int Cycles
    166, QMetaType::Double, 0x06015003, 		 // double PauseDelay
    50, QMetaType::Double, 0x06015003, 		 // double speed

 // enums: name, flags, count, data
    73, 0x0, 5, 111, 
    84, 0x0, 6, 121, 
    91, 0x0, 3, 133, 
    55, 0x0, 2, 139, 

 // enum data: key, value
    79, uint(EARTHLib::EnterpriseClientGE),
    80, uint(EARTHLib::ProGE),
    81, uint(EARTHLib::PlusGE),
    82, uint(EARTHLib::FreeGE),
    83, uint(EARTHLib::UnknownGE),
    85, uint(EARTHLib::GE_EC),
    86, uint(EARTHLib::GE_Pro),
    87, uint(EARTHLib::GE_Plus),
    88, uint(EARTHLib::GE_Free),
    89, uint(EARTHLib::GE_Plugin),
    90, uint(EARTHLib::UNKNOWN),
    92, uint(EARTHLib::TimeNegativeInfinityGE),
    93, uint(EARTHLib::TimeFiniteGE),
    94, uint(EARTHLib::TimePositiveInfinityGE),
    95, uint(EARTHLib::RelativeToGroundAltitudeGE),
    96, uint(EARTHLib::AbsoluteAltitudeGE),
    0 // eod
};

TourControllerGE::TourControllerGE(QObject *parent) :
    QAxObject(parent)
{
    setControl(QStringLiteral("{77c4c807-e257-43ad-bb3f-7ca88760bd29}"));
}

const QMetaObject TourControllerGE::staticMetaObject = {
{ &QObject::staticMetaObject,
qt_meta_stringdata_all.data,
qt_meta_data_EARTHLib__TourControllerGE, nullptr, nullptr, nullptr }
};

void *TourControllerGE::qt_metacast(const char *_clname)
{
    if (!_clname) return nullptr;
    if (!strcmp(_clname, "EARTHLib::TourControllerGE"))
        return static_cast<void*>(const_cast<TourControllerGE*>(this));
    return QAxObject::qt_metacast(_clname);
}
static const uint qt_meta_data_EARTHLib__SearchControllerGE[] = {

 // content:
    7, // revision
    191,  // classname
    1, 14, // classinfo
    7, 16, // methods
    0, 0, // properties
    4, 76, // enums/sets
    0, 0, // constructors
    0, // flags
    3, // signal count

 // classinfo: key, value
    1, 192, 

// signal: name, argc, parameters, tag, flags
    3, 4, 51, 4, 5,
    9, 1, 60, 4, 5,
    11, 3, 63, 4, 5,

// slot: name, argc, parameters, tag, flags
    170, 0, 70, 4, 9,
    171, 0, 71, 4, 9,
    172, 0, 72, 4, 9,
    173, 1, 73, 4, 9,

// signal: parameters
    QMetaType::Void, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, 5, 6, 7, 8,
    QMetaType::Void, QMetaType::QString, 10,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, QMetaType::VoidStar, 10, 12, 13,

// slot: parameters
    QMetaType::Void,
    0x80000000 | 24,
    QMetaType::Int,
    QMetaType::Void, QMetaType::QString, 174,

 // enums: name, flags, count, data
    73, 0x0, 5, 92, 
    84, 0x0, 6, 102, 
    91, 0x0, 3, 114, 
    55, 0x0, 2, 120, 

 // enum data: key, value
    79, uint(EARTHLib::EnterpriseClientGE),
    80, uint(EARTHLib::ProGE),
    81, uint(EARTHLib::PlusGE),
    82, uint(EARTHLib::FreeGE),
    83, uint(EARTHLib::UnknownGE),
    85, uint(EARTHLib::GE_EC),
    86, uint(EARTHLib::GE_Pro),
    87, uint(EARTHLib::GE_Plus),
    88, uint(EARTHLib::GE_Free),
    89, uint(EARTHLib::GE_Plugin),
    90, uint(EARTHLib::UNKNOWN),
    92, uint(EARTHLib::TimeNegativeInfinityGE),
    93, uint(EARTHLib::TimeFiniteGE),
    94, uint(EARTHLib::TimePositiveInfinityGE),
    95, uint(EARTHLib::RelativeToGroundAltitudeGE),
    96, uint(EARTHLib::AbsoluteAltitudeGE),
    0 // eod
};

SearchControllerGE::SearchControllerGE(QObject *parent) :
    QAxObject(parent)
{
    setControl(QStringLiteral("{a4f65992-5738-475b-9c16-cf102bcde153}"));
}

const QMetaObject SearchControllerGE::staticMetaObject = {
{ &QObject::staticMetaObject,
qt_meta_stringdata_all.data,
qt_meta_data_EARTHLib__SearchControllerGE, nullptr, nullptr, nullptr }
};

void *SearchControllerGE::qt_metacast(const char *_clname)
{
    if (!_clname) return nullptr;
    if (!strcmp(_clname, "EARTHLib::SearchControllerGE"))
        return static_cast<void*>(const_cast<SearchControllerGE*>(this));
    return QAxObject::qt_metacast(_clname);
}
static const uint qt_meta_data_EARTHLib__AnimationControllerGE[] = {

 // content:
    7, // revision
    193,  // classname
    1, 14, // classinfo
    6, 16, // methods
    2, 70, // properties
    4, 76, // enums/sets
    0, 0, // constructors
    0, // flags
    3, // signal count

 // classinfo: key, value
    1, 194, 

// signal: name, argc, parameters, tag, flags
    3, 4, 46, 4, 5,
    9, 1, 55, 4, 5,
    11, 3, 58, 4, 5,

// slot: name, argc, parameters, tag, flags
    176, 0, 65, 4, 9,
    177, 0, 66, 4, 9,
    178, 1, 67, 4, 9,

// signal: parameters
    QMetaType::Void, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, 5, 6, 7, 8,
    QMetaType::Void, QMetaType::QString, 10,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, QMetaType::VoidStar, 10, 12, 13,

// slot: parameters
    QMetaType::Void,
    QMetaType::Void,
    QMetaType::Void, 0x80000000 | 125, 179,

 // properties: name, type, flags
    179, 0x80000000 | 125, 0x00015003, 		 // ITimeIntervalGE* CurrentTimeInterval
    180, 0x80000000 | 125, 0x00005001, 		 // ITimeIntervalGE* SliderTimeInterval

 // enums: name, flags, count, data
    73, 0x0, 5, 92, 
    84, 0x0, 6, 102, 
    91, 0x0, 3, 114, 
    55, 0x0, 2, 120, 

 // enum data: key, value
    79, uint(EARTHLib::EnterpriseClientGE),
    80, uint(EARTHLib::ProGE),
    81, uint(EARTHLib::PlusGE),
    82, uint(EARTHLib::FreeGE),
    83, uint(EARTHLib::UnknownGE),
    85, uint(EARTHLib::GE_EC),
    86, uint(EARTHLib::GE_Pro),
    87, uint(EARTHLib::GE_Plus),
    88, uint(EARTHLib::GE_Free),
    89, uint(EARTHLib::GE_Plugin),
    90, uint(EARTHLib::UNKNOWN),
    92, uint(EARTHLib::TimeNegativeInfinityGE),
    93, uint(EARTHLib::TimeFiniteGE),
    94, uint(EARTHLib::TimePositiveInfinityGE),
    95, uint(EARTHLib::RelativeToGroundAltitudeGE),
    96, uint(EARTHLib::AbsoluteAltitudeGE),
    0 // eod
};

AnimationControllerGE::AnimationControllerGE(QObject *parent) :
    QAxObject(parent)
{
    setControl(QStringLiteral("{1a239250-b650-4b63-b4cf-7fcc4dc07dc6}"));
}

const QMetaObject AnimationControllerGE::staticMetaObject = {
{ &QObject::staticMetaObject,
qt_meta_stringdata_all.data,
qt_meta_data_EARTHLib__AnimationControllerGE, nullptr, nullptr, nullptr }
};

void *AnimationControllerGE::qt_metacast(const char *_clname)
{
    if (!_clname) return nullptr;
    if (!strcmp(_clname, "EARTHLib::AnimationControllerGE"))
        return static_cast<void*>(const_cast<AnimationControllerGE*>(this));
    return QAxObject::qt_metacast(_clname);
}
static const uint qt_meta_data_EARTHLib__FeatureGE[] = {

 // content:
    7, // revision
    195,  // classname
    1, 14, // classinfo
    7, 16, // methods
    5, 76, // properties
    4, 91, // enums/sets
    0, 0, // constructors
    0, // flags
    3, // signal count

 // classinfo: key, value
    1, 196, 

// signal: name, argc, parameters, tag, flags
    3, 4, 51, 4, 5,
    9, 1, 60, 4, 5,
    11, 3, 63, 4, 5,

// slot: name, argc, parameters, tag, flags
    117, 0, 70, 4, 9,
    118, 0, 71, 4, 9,
    119, 0, 72, 4, 9,
    120, 1, 73, 4, 9,

// signal: parameters
    QMetaType::Void, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, 5, 6, 7, 8,
    QMetaType::Void, QMetaType::QString, 10,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, QMetaType::VoidStar, 10, 12, 13,

// slot: parameters
    0x80000000 | 24,
    0x80000000 | 18,
    QMetaType::Void,
    QMetaType::Void, QMetaType::Int, 121,

 // properties: name, type, flags
    122, QMetaType::Int, 0x02005001, 		 // int HasView
    123, QMetaType::Int, 0x02005001, 		 // int Highlighted
    21, QMetaType::QString, 0x0a005001, 		 // QString Name
    124, 0x80000000 | 125, 0x00005001, 		 // ITimeIntervalGE* TimeInterval
    121, QMetaType::Int, 0x02015003, 		 // int Visibility

 // enums: name, flags, count, data
    73, 0x0, 5, 107, 
    84, 0x0, 6, 117, 
    91, 0x0, 3, 129, 
    55, 0x0, 2, 135, 

 // enum data: key, value
    79, uint(EARTHLib::EnterpriseClientGE),
    80, uint(EARTHLib::ProGE),
    81, uint(EARTHLib::PlusGE),
    82, uint(EARTHLib::FreeGE),
    83, uint(EARTHLib::UnknownGE),
    85, uint(EARTHLib::GE_EC),
    86, uint(EARTHLib::GE_Pro),
    87, uint(EARTHLib::GE_Plus),
    88, uint(EARTHLib::GE_Free),
    89, uint(EARTHLib::GE_Plugin),
    90, uint(EARTHLib::UNKNOWN),
    92, uint(EARTHLib::TimeNegativeInfinityGE),
    93, uint(EARTHLib::TimeFiniteGE),
    94, uint(EARTHLib::TimePositiveInfinityGE),
    95, uint(EARTHLib::RelativeToGroundAltitudeGE),
    96, uint(EARTHLib::AbsoluteAltitudeGE),
    0 // eod
};

FeatureGE::FeatureGE(QObject *parent) :
    QAxObject(parent)
{
    setControl(QStringLiteral("{cbd4fb70-f00b-4963-b249-4b056e6a981a}"));
}

const QMetaObject FeatureGE::staticMetaObject = {
{ &QObject::staticMetaObject,
qt_meta_stringdata_all.data,
qt_meta_data_EARTHLib__FeatureGE, nullptr, nullptr, nullptr }
};

void *FeatureGE::qt_metacast(const char *_clname)
{
    if (!_clname) return nullptr;
    if (!strcmp(_clname, "EARTHLib::FeatureGE"))
        return static_cast<void*>(const_cast<FeatureGE*>(this));
    return QAxObject::qt_metacast(_clname);
}
static const uint qt_meta_data_EARTHLib__FeatureCollectionGE[] = {

 // content:
    7, // revision
    197,  // classname
    1, 14, // classinfo
    4, 16, // methods
    2, 58, // properties
    4, 64, // enums/sets
    0, 0, // constructors
    0, // flags
    3, // signal count

 // classinfo: key, value
    1, 198, 

// signal: name, argc, parameters, tag, flags
    3, 4, 36, 4, 5,
    9, 1, 45, 4, 5,
    11, 3, 48, 4, 5,

// slot: name, argc, parameters, tag, flags
    127, 1, 55, 4, 9,

// signal: parameters
    QMetaType::Void, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, 5, 6, 7, 8,
    QMetaType::Void, QMetaType::QString, 10,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, QMetaType::VoidStar, 10, 12, 13,

// slot: parameters
    0x80000000 | 18, QMetaType::Int, 128,

 // properties: name, type, flags
    129, QMetaType::Int, 0x02005001, 		 // int Count
    130, 0x80000000 | 131, 0x00005001, 		 // IUnknown* _NewEnum

 // enums: name, flags, count, data
    73, 0x0, 5, 80, 
    84, 0x0, 6, 90, 
    91, 0x0, 3, 102, 
    55, 0x0, 2, 108, 

 // enum data: key, value
    79, uint(EARTHLib::EnterpriseClientGE),
    80, uint(EARTHLib::ProGE),
    81, uint(EARTHLib::PlusGE),
    82, uint(EARTHLib::FreeGE),
    83, uint(EARTHLib::UnknownGE),
    85, uint(EARTHLib::GE_EC),
    86, uint(EARTHLib::GE_Pro),
    87, uint(EARTHLib::GE_Plus),
    88, uint(EARTHLib::GE_Free),
    89, uint(EARTHLib::GE_Plugin),
    90, uint(EARTHLib::UNKNOWN),
    92, uint(EARTHLib::TimeNegativeInfinityGE),
    93, uint(EARTHLib::TimeFiniteGE),
    94, uint(EARTHLib::TimePositiveInfinityGE),
    95, uint(EARTHLib::RelativeToGroundAltitudeGE),
    96, uint(EARTHLib::AbsoluteAltitudeGE),
    0 // eod
};

FeatureCollectionGE::FeatureCollectionGE(QObject *parent) :
    QAxObject(parent)
{
    setControl(QStringLiteral("{9059c329-4661-49b2-9984-8753c45db7b9}"));
}

const QMetaObject FeatureCollectionGE::staticMetaObject = {
{ &QObject::staticMetaObject,
qt_meta_stringdata_all.data,
qt_meta_data_EARTHLib__FeatureCollectionGE, nullptr, nullptr, nullptr }
};

void *FeatureCollectionGE::qt_metacast(const char *_clname)
{
    if (!_clname) return nullptr;
    if (!strcmp(_clname, "EARTHLib::FeatureCollectionGE"))
        return static_cast<void*>(const_cast<FeatureCollectionGE*>(this));
    return QAxObject::qt_metacast(_clname);
}
static const uint qt_meta_data_EARTHLib__PointOnTerrainGE[] = {

 // content:
    7, // revision
    199,  // classname
    1, 14, // classinfo
    3, 16, // methods
    5, 50, // properties
    4, 65, // enums/sets
    0, 0, // constructors
    0, // flags
    3, // signal count

 // classinfo: key, value
    1, 200, 

// signal: name, argc, parameters, tag, flags
    3, 4, 31, 4, 5,
    9, 1, 40, 4, 5,
    11, 3, 43, 4, 5,

// signal: parameters
    QMetaType::Void, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, 5, 6, 7, 8,
    QMetaType::Void, QMetaType::QString, 10,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, QMetaType::VoidStar, 10, 12, 13,

 // properties: name, type, flags
    156, QMetaType::Double, 0x06005001, 		 // double Altitude
    157, QMetaType::Double, 0x06005001, 		 // double Latitude
    158, QMetaType::Double, 0x06005001, 		 // double Longitude
    159, QMetaType::Int, 0x02005001, 		 // int ProjectedOntoGlobe
    160, QMetaType::Int, 0x02005001, 		 // int ZeroElevationExaggeration

 // enums: name, flags, count, data
    73, 0x0, 5, 81, 
    84, 0x0, 6, 91, 
    91, 0x0, 3, 103, 
    55, 0x0, 2, 109, 

 // enum data: key, value
    79, uint(EARTHLib::EnterpriseClientGE),
    80, uint(EARTHLib::ProGE),
    81, uint(EARTHLib::PlusGE),
    82, uint(EARTHLib::FreeGE),
    83, uint(EARTHLib::UnknownGE),
    85, uint(EARTHLib::GE_EC),
    86, uint(EARTHLib::GE_Pro),
    87, uint(EARTHLib::GE_Plus),
    88, uint(EARTHLib::GE_Free),
    89, uint(EARTHLib::GE_Plugin),
    90, uint(EARTHLib::UNKNOWN),
    92, uint(EARTHLib::TimeNegativeInfinityGE),
    93, uint(EARTHLib::TimeFiniteGE),
    94, uint(EARTHLib::TimePositiveInfinityGE),
    95, uint(EARTHLib::RelativeToGroundAltitudeGE),
    96, uint(EARTHLib::AbsoluteAltitudeGE),
    0 // eod
};

PointOnTerrainGE::PointOnTerrainGE(QObject *parent) :
    QAxObject(parent)
{
    setControl(QStringLiteral("{1796a329-04c1-4c07-b28e-e4a807935c06}"));
}

const QMetaObject PointOnTerrainGE::staticMetaObject = {
{ &QObject::staticMetaObject,
qt_meta_stringdata_all.data,
qt_meta_data_EARTHLib__PointOnTerrainGE, nullptr, nullptr, nullptr }
};

void *PointOnTerrainGE::qt_metacast(const char *_clname)
{
    if (!_clname) return nullptr;
    if (!strcmp(_clname, "EARTHLib::PointOnTerrainGE"))
        return static_cast<void*>(const_cast<PointOnTerrainGE*>(this));
    return QAxObject::qt_metacast(_clname);
}
static const uint qt_meta_data_EARTHLib__KHInterface[] = {

 // content:
    7, // revision
    201,  // classname
    1, 14, // classinfo
    17, 16, // methods
    3, 190, // properties
    4, 199, // enums/sets
    0, 0, // constructors
    0, // flags
    3, // signal count

 // classinfo: key, value
    1, 202, 

// signal: name, argc, parameters, tag, flags
    3, 4, 101, 4, 5,
    9, 1, 110, 4, 5,
    11, 3, 113, 4, 5,

// slot: name, argc, parameters, tag, flags
    20, 1, 120, 4, 9,
    27, 2, 123, 4, 9,
    204, 1, 128, 4, 9,
    205, 1, 131, 4, 9,
    206, 0, 134, 4, 9,
    44, 2, 135, 4, 9,
    46, 1, 140, 4, 9,
    62, 2, 143, 4, 9,
    207, 2, 148, 4, 9,
    210, 1, 153, 4, 9,
    213, 4, 156, 4, 9,
    220, 1, 165, 4, 9,
    221, 3, 168, 4, 9,
    223, 7, 175, 4, 9,

// signal: parameters
    QMetaType::Void, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, 5, 6, 7, 8,
    QMetaType::Void, QMetaType::QString, 10,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, QMetaType::VoidStar, 10, 12, 13,

// slot: parameters
    0x80000000 | 203, QMetaType::QString, 21,
    QMetaType::QVariantList, QMetaType::Double, QMetaType::Double, 29, 30,
    QMetaType::Void, 0x80000000 | 37, 38,
    QMetaType::Void, QMetaType::QString, 42,
    QMetaType::Void,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, 42, 45,
    QMetaType::Void, QMetaType::Double, 47,
    QMetaType::Void, 0x80000000 | 203, QMetaType::Double, 63, 50,
    QMetaType::Void, QMetaType::Int, QMetaType::Int, 208, 209,
    0x80000000 | 211, QMetaType::Int, 212,
    QMetaType::Void, 0x80000000 | 214, 0x80000000 | 214, 0x80000000 | 214, 0x80000000 | 218, 215, 216, 217, 219,
    QMetaType::Void, 0x80000000 | 214, 34,
    QMetaType::Void, 0x80000000 | 211, QMetaType::Int, QMetaType::Double, 222, 212, 50,
    QMetaType::Void, QMetaType::Double, QMetaType::Double, QMetaType::Double, QMetaType::Double, QMetaType::Double, QMetaType::Int, QMetaType::Double, 52, 53, 57, 58, 59, 212, 50,

 // properties: name, type, flags
    47, QMetaType::Double, 0x06015003, 		 // double AutoPilotSpeed
    69, QMetaType::Int, 0x02005001, 		 // int StreamingProgressPercentage
    224, 0x80000000 | 225, 0x00005001, 		 // IKHViewExtents* currentViewExtents

 // enums: name, flags, count, data
    73, 0x0, 5, 215, 
    84, 0x0, 6, 225, 
    91, 0x0, 3, 237, 
    55, 0x0, 2, 243, 

 // enum data: key, value
    79, uint(EARTHLib::EnterpriseClientGE),
    80, uint(EARTHLib::ProGE),
    81, uint(EARTHLib::PlusGE),
    82, uint(EARTHLib::FreeGE),
    83, uint(EARTHLib::UnknownGE),
    85, uint(EARTHLib::GE_EC),
    86, uint(EARTHLib::GE_Pro),
    87, uint(EARTHLib::GE_Plus),
    88, uint(EARTHLib::GE_Free),
    89, uint(EARTHLib::GE_Plugin),
    90, uint(EARTHLib::UNKNOWN),
    92, uint(EARTHLib::TimeNegativeInfinityGE),
    93, uint(EARTHLib::TimeFiniteGE),
    94, uint(EARTHLib::TimePositiveInfinityGE),
    95, uint(EARTHLib::RelativeToGroundAltitudeGE),
    96, uint(EARTHLib::AbsoluteAltitudeGE),
    0 // eod
};

KHInterface::KHInterface(QObject *parent) :
    QAxObject(parent)
{
    setControl(QStringLiteral("{afd07a5e-3e20-4d77-825c-2f6d1a50be5b}"));
}

const QMetaObject KHInterface::staticMetaObject = {
{ &QObject::staticMetaObject,
qt_meta_stringdata_all.data,
qt_meta_data_EARTHLib__KHInterface, nullptr, nullptr, nullptr }
};

void *KHInterface::qt_metacast(const char *_clname)
{
    if (!_clname) return nullptr;
    if (!strcmp(_clname, "EARTHLib::KHInterface"))
        return static_cast<void*>(const_cast<KHInterface*>(this));
    return QAxObject::qt_metacast(_clname);
}
static const uint qt_meta_data_EARTHLib__IKHInterface[] = {

 // content:
    7, // revision
    226,  // classname
    0, 0, // classinfo
    17, 14, // methods
    4, 188, // properties
    4, 200, // enums/sets
    0, 0, // constructors
    0, // flags
    3, // signal count

// signal: name, argc, parameters, tag, flags
    3, 4, 99, 4, 5,
    9, 1, 108, 4, 5,
    11, 3, 111, 4, 5,

// slot: name, argc, parameters, tag, flags
    20, 1, 118, 4, 9,
    27, 2, 121, 4, 9,
    204, 1, 126, 4, 9,
    205, 1, 129, 4, 9,
    206, 0, 132, 4, 9,
    44, 2, 133, 4, 9,
    46, 1, 138, 4, 9,
    62, 2, 141, 4, 9,
    207, 2, 146, 4, 9,
    210, 1, 151, 4, 9,
    213, 4, 154, 4, 9,
    220, 1, 163, 4, 9,
    221, 3, 166, 4, 9,
    223, 7, 173, 4, 9,

// signal: parameters
    QMetaType::Void, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, 5, 6, 7, 8,
    QMetaType::Void, QMetaType::QString, 10,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, QMetaType::VoidStar, 10, 12, 13,

// slot: parameters
    0x80000000 | 203, QMetaType::QString, 21,
    QMetaType::QVariantList, QMetaType::Double, QMetaType::Double, 29, 30,
    QMetaType::Void, 0x80000000 | 37, 38,
    QMetaType::Void, QMetaType::QString, 42,
    QMetaType::Void,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, 42, 45,
    QMetaType::Void, QMetaType::Double, 47,
    QMetaType::Void, 0x80000000 | 203, QMetaType::Double, 63, 50,
    QMetaType::Void, QMetaType::Int, QMetaType::Int, 208, 209,
    0x80000000 | 211, QMetaType::Int, 212,
    QMetaType::Void, 0x80000000 | 214, 0x80000000 | 214, 0x80000000 | 214, 0x80000000 | 218, 215, 216, 217, 219,
    QMetaType::Void, 0x80000000 | 214, 34,
    QMetaType::Void, 0x80000000 | 211, QMetaType::Int, QMetaType::Double, 222, 212, 50,
    QMetaType::Void, QMetaType::Double, QMetaType::Double, QMetaType::Double, QMetaType::Double, QMetaType::Double, QMetaType::Int, QMetaType::Double, 52, 53, 57, 58, 59, 212, 50,

 // properties: name, type, flags
    47, QMetaType::Double, 0x06015003, 		 // double AutoPilotSpeed
    69, QMetaType::Int, 0x02005001, 		 // int StreamingProgressPercentage
    98, QMetaType::QString, 0x0a055003, 		 // QString control
    224, 0x80000000 | 225, 0x00005001, 		 // IKHViewExtents* currentViewExtents

 // enums: name, flags, count, data
    73, 0x0, 5, 216, 
    84, 0x0, 6, 226, 
    91, 0x0, 3, 238, 
    55, 0x0, 2, 244, 

 // enum data: key, value
    79, uint(EARTHLib::EnterpriseClientGE),
    80, uint(EARTHLib::ProGE),
    81, uint(EARTHLib::PlusGE),
    82, uint(EARTHLib::FreeGE),
    83, uint(EARTHLib::UnknownGE),
    85, uint(EARTHLib::GE_EC),
    86, uint(EARTHLib::GE_Pro),
    87, uint(EARTHLib::GE_Plus),
    88, uint(EARTHLib::GE_Free),
    89, uint(EARTHLib::GE_Plugin),
    90, uint(EARTHLib::UNKNOWN),
    92, uint(EARTHLib::TimeNegativeInfinityGE),
    93, uint(EARTHLib::TimeFiniteGE),
    94, uint(EARTHLib::TimePositiveInfinityGE),
    95, uint(EARTHLib::RelativeToGroundAltitudeGE),
    96, uint(EARTHLib::AbsoluteAltitudeGE),
    0 // eod
};

IKHInterface::IKHInterface(IDispatch *subobject, QAxObject *parent) :
    QAxObject(subobject, parent)
{
    internalRelease();
}

const QMetaObject IKHInterface::staticMetaObject = {
{ &QObject::staticMetaObject,
qt_meta_stringdata_all.data,
qt_meta_data_EARTHLib__IKHInterface, nullptr, nullptr, nullptr }
};

void *IKHInterface::qt_metacast(const char *_clname)
{
    if (!_clname) return nullptr;
    if (!strcmp(_clname, "EARTHLib::IKHInterface"))
        return static_cast<void*>(const_cast<IKHInterface*>(this));
    return QAxObject::qt_metacast(_clname);
}
static const uint qt_meta_data_EARTHLib__IKHViewInfo[] = {

 // content:
    7, // revision
    227,  // classname
    0, 0, // classinfo
    8, 14, // methods
    6, 88, // properties
    4, 106, // enums/sets
    0, 0, // constructors
    0, // flags
    3, // signal count

// signal: name, argc, parameters, tag, flags
    3, 4, 54, 4, 5,
    9, 1, 63, 4, 5,
    11, 3, 66, 4, 5,

// slot: name, argc, parameters, tag, flags
    100, 1, 73, 4, 9,
    228, 1, 76, 4, 9,
    229, 1, 79, 4, 9,
    109, 1, 82, 4, 9,
    110, 1, 85, 4, 9,

// signal: parameters
    QMetaType::Void, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, 5, 6, 7, 8,
    QMetaType::Void, QMetaType::QString, 10,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, QMetaType::VoidStar, 10, 12, 13,

// slot: parameters
    QMetaType::Void, QMetaType::Double, 59,
    QMetaType::Void, QMetaType::Double, 157,
    QMetaType::Void, QMetaType::Double, 158,
    QMetaType::Void, QMetaType::Double, 57,
    QMetaType::Void, QMetaType::Double, 58,

 // properties: name, type, flags
    59, QMetaType::Double, 0x06015003, 		 // double Azimuth
    157, QMetaType::Double, 0x06015003, 		 // double Latitude
    158, QMetaType::Double, 0x06015003, 		 // double Longitude
    57, QMetaType::Double, 0x06015003, 		 // double Range
    58, QMetaType::Double, 0x06015003, 		 // double Tilt
    98, QMetaType::QString, 0x0a055003, 		 // QString control

 // enums: name, flags, count, data
    73, 0x0, 5, 122, 
    84, 0x0, 6, 132, 
    91, 0x0, 3, 144, 
    55, 0x0, 2, 150, 

 // enum data: key, value
    79, uint(EARTHLib::EnterpriseClientGE),
    80, uint(EARTHLib::ProGE),
    81, uint(EARTHLib::PlusGE),
    82, uint(EARTHLib::FreeGE),
    83, uint(EARTHLib::UnknownGE),
    85, uint(EARTHLib::GE_EC),
    86, uint(EARTHLib::GE_Pro),
    87, uint(EARTHLib::GE_Plus),
    88, uint(EARTHLib::GE_Free),
    89, uint(EARTHLib::GE_Plugin),
    90, uint(EARTHLib::UNKNOWN),
    92, uint(EARTHLib::TimeNegativeInfinityGE),
    93, uint(EARTHLib::TimeFiniteGE),
    94, uint(EARTHLib::TimePositiveInfinityGE),
    95, uint(EARTHLib::RelativeToGroundAltitudeGE),
    96, uint(EARTHLib::AbsoluteAltitudeGE),
    0 // eod
};

IKHViewInfo::IKHViewInfo(IDispatch *subobject, QAxObject *parent) :
    QAxObject(subobject, parent)
{
    internalRelease();
}

const QMetaObject IKHViewInfo::staticMetaObject = {
{ &QObject::staticMetaObject,
qt_meta_stringdata_all.data,
qt_meta_data_EARTHLib__IKHViewInfo, nullptr, nullptr, nullptr }
};

void *IKHViewInfo::qt_metacast(const char *_clname)
{
    if (!_clname) return nullptr;
    if (!strcmp(_clname, "EARTHLib::IKHViewInfo"))
        return static_cast<void*>(const_cast<IKHViewInfo*>(this));
    return QAxObject::qt_metacast(_clname);
}
static const uint qt_meta_data_EARTHLib__IKHViewExtents[] = {

 // content:
    7, // revision
    230,  // classname
    0, 0, // classinfo
    3, 14, // methods
    5, 48, // properties
    4, 63, // enums/sets
    0, 0, // constructors
    0, // flags
    3, // signal count

// signal: name, argc, parameters, tag, flags
    3, 4, 29, 4, 5,
    9, 1, 38, 4, 5,
    11, 3, 41, 4, 5,

// signal: parameters
    QMetaType::Void, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, 5, 6, 7, 8,
    QMetaType::Void, QMetaType::QString, 10,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, QMetaType::VoidStar, 10, 12, 13,

 // properties: name, type, flags
    112, QMetaType::Double, 0x06005001, 		 // double East
    113, QMetaType::Double, 0x06005001, 		 // double North
    114, QMetaType::Double, 0x06005001, 		 // double South
    115, QMetaType::Double, 0x06005001, 		 // double West
    98, QMetaType::QString, 0x0a055003, 		 // QString control

 // enums: name, flags, count, data
    73, 0x0, 5, 79, 
    84, 0x0, 6, 89, 
    91, 0x0, 3, 101, 
    55, 0x0, 2, 107, 

 // enum data: key, value
    79, uint(EARTHLib::EnterpriseClientGE),
    80, uint(EARTHLib::ProGE),
    81, uint(EARTHLib::PlusGE),
    82, uint(EARTHLib::FreeGE),
    83, uint(EARTHLib::UnknownGE),
    85, uint(EARTHLib::GE_EC),
    86, uint(EARTHLib::GE_Pro),
    87, uint(EARTHLib::GE_Plus),
    88, uint(EARTHLib::GE_Free),
    89, uint(EARTHLib::GE_Plugin),
    90, uint(EARTHLib::UNKNOWN),
    92, uint(EARTHLib::TimeNegativeInfinityGE),
    93, uint(EARTHLib::TimeFiniteGE),
    94, uint(EARTHLib::TimePositiveInfinityGE),
    95, uint(EARTHLib::RelativeToGroundAltitudeGE),
    96, uint(EARTHLib::AbsoluteAltitudeGE),
    0 // eod
};

IKHViewExtents::IKHViewExtents(IDispatch *subobject, QAxObject *parent) :
    QAxObject(subobject, parent)
{
    internalRelease();
}

const QMetaObject IKHViewExtents::staticMetaObject = {
{ &QObject::staticMetaObject,
qt_meta_stringdata_all.data,
qt_meta_data_EARTHLib__IKHViewExtents, nullptr, nullptr, nullptr }
};

void *IKHViewExtents::qt_metacast(const char *_clname)
{
    if (!_clname) return nullptr;
    if (!strcmp(_clname, "EARTHLib::IKHViewExtents"))
        return static_cast<void*>(const_cast<IKHViewExtents*>(this));
    return QAxObject::qt_metacast(_clname);
}
static const uint qt_meta_data_EARTHLib__IKHFeature[] = {

 // content:
    7, // revision
    231,  // classname
    0, 0, // classinfo
    4, 14, // methods
    3, 56, // properties
    4, 65, // enums/sets
    0, 0, // constructors
    0, // flags
    3, // signal count

// signal: name, argc, parameters, tag, flags
    3, 4, 34, 4, 5,
    9, 1, 43, 4, 5,
    11, 3, 46, 4, 5,

// slot: name, argc, parameters, tag, flags
    120, 1, 53, 4, 9,

// signal: parameters
    QMetaType::Void, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, 5, 6, 7, 8,
    QMetaType::Void, QMetaType::QString, 10,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, QMetaType::VoidStar, 10, 12, 13,

// slot: parameters
    QMetaType::Void, QMetaType::Int, 121,

 // properties: name, type, flags
    122, QMetaType::Int, 0x02005001, 		 // int HasView
    121, QMetaType::Int, 0x02015003, 		 // int Visibility
    98, QMetaType::QString, 0x0a055003, 		 // QString control

 // enums: name, flags, count, data
    73, 0x0, 5, 81, 
    84, 0x0, 6, 91, 
    91, 0x0, 3, 103, 
    55, 0x0, 2, 109, 

 // enum data: key, value
    79, uint(EARTHLib::EnterpriseClientGE),
    80, uint(EARTHLib::ProGE),
    81, uint(EARTHLib::PlusGE),
    82, uint(EARTHLib::FreeGE),
    83, uint(EARTHLib::UnknownGE),
    85, uint(EARTHLib::GE_EC),
    86, uint(EARTHLib::GE_Pro),
    87, uint(EARTHLib::GE_Plus),
    88, uint(EARTHLib::GE_Free),
    89, uint(EARTHLib::GE_Plugin),
    90, uint(EARTHLib::UNKNOWN),
    92, uint(EARTHLib::TimeNegativeInfinityGE),
    93, uint(EARTHLib::TimeFiniteGE),
    94, uint(EARTHLib::TimePositiveInfinityGE),
    95, uint(EARTHLib::RelativeToGroundAltitudeGE),
    96, uint(EARTHLib::AbsoluteAltitudeGE),
    0 // eod
};

IKHFeature::IKHFeature(IDispatch *subobject, QAxObject *parent) :
    QAxObject(subobject, parent)
{
    internalRelease();
}

const QMetaObject IKHFeature::staticMetaObject = {
{ &QObject::staticMetaObject,
qt_meta_stringdata_all.data,
qt_meta_data_EARTHLib__IKHFeature, nullptr, nullptr, nullptr }
};

void *IKHFeature::qt_metacast(const char *_clname)
{
    if (!_clname) return nullptr;
    if (!strcmp(_clname, "EARTHLib::IKHFeature"))
        return static_cast<void*>(const_cast<IKHFeature*>(this));
    return QAxObject::qt_metacast(_clname);
}
static const uint qt_meta_data_EARTHLib__KHViewInfo[] = {

 // content:
    7, // revision
    232,  // classname
    1, 14, // classinfo
    8, 16, // methods
    5, 90, // properties
    4, 105, // enums/sets
    0, 0, // constructors
    0, // flags
    3, // signal count

 // classinfo: key, value
    1, 233, 

// signal: name, argc, parameters, tag, flags
    3, 4, 56, 4, 5,
    9, 1, 65, 4, 5,
    11, 3, 68, 4, 5,

// slot: name, argc, parameters, tag, flags
    100, 1, 75, 4, 9,
    228, 1, 78, 4, 9,
    229, 1, 81, 4, 9,
    109, 1, 84, 4, 9,
    110, 1, 87, 4, 9,

// signal: parameters
    QMetaType::Void, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, 5, 6, 7, 8,
    QMetaType::Void, QMetaType::QString, 10,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, QMetaType::VoidStar, 10, 12, 13,

// slot: parameters
    QMetaType::Void, QMetaType::Double, 59,
    QMetaType::Void, QMetaType::Double, 157,
    QMetaType::Void, QMetaType::Double, 158,
    QMetaType::Void, QMetaType::Double, 57,
    QMetaType::Void, QMetaType::Double, 58,

 // properties: name, type, flags
    59, QMetaType::Double, 0x06015003, 		 // double Azimuth
    157, QMetaType::Double, 0x06015003, 		 // double Latitude
    158, QMetaType::Double, 0x06015003, 		 // double Longitude
    57, QMetaType::Double, 0x06015003, 		 // double Range
    58, QMetaType::Double, 0x06015003, 		 // double Tilt

 // enums: name, flags, count, data
    73, 0x0, 5, 121, 
    84, 0x0, 6, 131, 
    91, 0x0, 3, 143, 
    55, 0x0, 2, 149, 

 // enum data: key, value
    79, uint(EARTHLib::EnterpriseClientGE),
    80, uint(EARTHLib::ProGE),
    81, uint(EARTHLib::PlusGE),
    82, uint(EARTHLib::FreeGE),
    83, uint(EARTHLib::UnknownGE),
    85, uint(EARTHLib::GE_EC),
    86, uint(EARTHLib::GE_Pro),
    87, uint(EARTHLib::GE_Plus),
    88, uint(EARTHLib::GE_Free),
    89, uint(EARTHLib::GE_Plugin),
    90, uint(EARTHLib::UNKNOWN),
    92, uint(EARTHLib::TimeNegativeInfinityGE),
    93, uint(EARTHLib::TimeFiniteGE),
    94, uint(EARTHLib::TimePositiveInfinityGE),
    95, uint(EARTHLib::RelativeToGroundAltitudeGE),
    96, uint(EARTHLib::AbsoluteAltitudeGE),
    0 // eod
};

KHViewInfo::KHViewInfo(QObject *parent) :
    QAxObject(parent)
{
    setControl(QStringLiteral("{a2d4475b-c9aa-48e2-a029-1db829dacf7b}"));
}

const QMetaObject KHViewInfo::staticMetaObject = {
{ &QObject::staticMetaObject,
qt_meta_stringdata_all.data,
qt_meta_data_EARTHLib__KHViewInfo, nullptr, nullptr, nullptr }
};

void *KHViewInfo::qt_metacast(const char *_clname)
{
    if (!_clname) return nullptr;
    if (!strcmp(_clname, "EARTHLib::KHViewInfo"))
        return static_cast<void*>(const_cast<KHViewInfo*>(this));
    return QAxObject::qt_metacast(_clname);
}
static const uint qt_meta_data_EARTHLib__KHViewExtents[] = {

 // content:
    7, // revision
    234,  // classname
    1, 14, // classinfo
    3, 16, // methods
    4, 50, // properties
    4, 62, // enums/sets
    0, 0, // constructors
    0, // flags
    3, // signal count

 // classinfo: key, value
    1, 235, 

// signal: name, argc, parameters, tag, flags
    3, 4, 31, 4, 5,
    9, 1, 40, 4, 5,
    11, 3, 43, 4, 5,

// signal: parameters
    QMetaType::Void, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, 5, 6, 7, 8,
    QMetaType::Void, QMetaType::QString, 10,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, QMetaType::VoidStar, 10, 12, 13,

 // properties: name, type, flags
    112, QMetaType::Double, 0x06005001, 		 // double East
    113, QMetaType::Double, 0x06005001, 		 // double North
    114, QMetaType::Double, 0x06005001, 		 // double South
    115, QMetaType::Double, 0x06005001, 		 // double West

 // enums: name, flags, count, data
    73, 0x0, 5, 78, 
    84, 0x0, 6, 88, 
    91, 0x0, 3, 100, 
    55, 0x0, 2, 106, 

 // enum data: key, value
    79, uint(EARTHLib::EnterpriseClientGE),
    80, uint(EARTHLib::ProGE),
    81, uint(EARTHLib::PlusGE),
    82, uint(EARTHLib::FreeGE),
    83, uint(EARTHLib::UnknownGE),
    85, uint(EARTHLib::GE_EC),
    86, uint(EARTHLib::GE_Pro),
    87, uint(EARTHLib::GE_Plus),
    88, uint(EARTHLib::GE_Free),
    89, uint(EARTHLib::GE_Plugin),
    90, uint(EARTHLib::UNKNOWN),
    92, uint(EARTHLib::TimeNegativeInfinityGE),
    93, uint(EARTHLib::TimeFiniteGE),
    94, uint(EARTHLib::TimePositiveInfinityGE),
    95, uint(EARTHLib::RelativeToGroundAltitudeGE),
    96, uint(EARTHLib::AbsoluteAltitudeGE),
    0 // eod
};

KHViewExtents::KHViewExtents(QObject *parent) :
    QAxObject(parent)
{
    setControl(QStringLiteral("{63e6be14-a742-4eea-8af3-0ec39f10f850}"));
}

const QMetaObject KHViewExtents::staticMetaObject = {
{ &QObject::staticMetaObject,
qt_meta_stringdata_all.data,
qt_meta_data_EARTHLib__KHViewExtents, nullptr, nullptr, nullptr }
};

void *KHViewExtents::qt_metacast(const char *_clname)
{
    if (!_clname) return nullptr;
    if (!strcmp(_clname, "EARTHLib::KHViewExtents"))
        return static_cast<void*>(const_cast<KHViewExtents*>(this));
    return QAxObject::qt_metacast(_clname);
}
static const uint qt_meta_data_EARTHLib__KHFeature[] = {

 // content:
    7, // revision
    236,  // classname
    1, 14, // classinfo
    4, 16, // methods
    2, 58, // properties
    4, 64, // enums/sets
    0, 0, // constructors
    0, // flags
    3, // signal count

 // classinfo: key, value
    1, 237, 

// signal: name, argc, parameters, tag, flags
    3, 4, 36, 4, 5,
    9, 1, 45, 4, 5,
    11, 3, 48, 4, 5,

// slot: name, argc, parameters, tag, flags
    120, 1, 55, 4, 9,

// signal: parameters
    QMetaType::Void, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, 5, 6, 7, 8,
    QMetaType::Void, QMetaType::QString, 10,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, QMetaType::VoidStar, 10, 12, 13,

// slot: parameters
    QMetaType::Void, QMetaType::Int, 121,

 // properties: name, type, flags
    122, QMetaType::Int, 0x02005001, 		 // int HasView
    121, QMetaType::Int, 0x02015003, 		 // int Visibility

 // enums: name, flags, count, data
    73, 0x0, 5, 80, 
    84, 0x0, 6, 90, 
    91, 0x0, 3, 102, 
    55, 0x0, 2, 108, 

 // enum data: key, value
    79, uint(EARTHLib::EnterpriseClientGE),
    80, uint(EARTHLib::ProGE),
    81, uint(EARTHLib::PlusGE),
    82, uint(EARTHLib::FreeGE),
    83, uint(EARTHLib::UnknownGE),
    85, uint(EARTHLib::GE_EC),
    86, uint(EARTHLib::GE_Pro),
    87, uint(EARTHLib::GE_Plus),
    88, uint(EARTHLib::GE_Free),
    89, uint(EARTHLib::GE_Plugin),
    90, uint(EARTHLib::UNKNOWN),
    92, uint(EARTHLib::TimeNegativeInfinityGE),
    93, uint(EARTHLib::TimeFiniteGE),
    94, uint(EARTHLib::TimePositiveInfinityGE),
    95, uint(EARTHLib::RelativeToGroundAltitudeGE),
    96, uint(EARTHLib::AbsoluteAltitudeGE),
    0 // eod
};

KHFeature::KHFeature(QObject *parent) :
    QAxObject(parent)
{
    setControl(QStringLiteral("{b153d707-447a-4538-913e-6146b3fdee02}"));
}

const QMetaObject KHFeature::staticMetaObject = {
{ &QObject::staticMetaObject,
qt_meta_stringdata_all.data,
qt_meta_data_EARTHLib__KHFeature, nullptr, nullptr, nullptr }
};

void *KHFeature::qt_metacast(const char *_clname)
{
    if (!_clname) return nullptr;
    if (!strcmp(_clname, "EARTHLib::KHFeature"))
        return static_cast<void*>(const_cast<KHFeature*>(this));
    return QAxObject::qt_metacast(_clname);
}

